<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class InstructorSeeder extends Seeder
{
    public function run(): void
    {
        $instructors = [
            ['A. Ka Tat Tsang', 'a.ka.tat.tsang@instructor.com'],
            ['A. Freddie Page', 'a.freddie.page@instructor.com'],
            ['AICPA', 'aicpa@instructor.com'],
            ['AMMAR ALSALKA', 'ammar.alsalka@instructor.com'],
            ['Aaron Ridley', 'aaron.ridley@instructor.com'],
            ['Aaron Ritchie', 'aaron.ritchie@instructor.com'],
            ['Aaron Saray', 'aaron.saray@instructor.com'],
            ['Aarti Bagul', 'aarti.bagul@instructor.com'],
            ['Abdallah Mohamed', 'abdallah.mohamed@instructor.com'],
            ['Abel Rodriguez', 'abel.rodriguez@instructor.com'],
            ['Abhishek Gagneja', 'abhishek.gagneja@instructor.com'],
            ['Abhishek Jha', 'abhishek.jha@instructor.com'],
            ['Adam Filion', 'adam.filion@instructor.com'],
            ['Adam Stephenson', 'adam.stephenson@instructor.com'],
            ['Adam White', 'adam.white@instructor.com'],
            ['Adrienne Fairhall', 'adrienne.fairhall@instructor.com'],
            ['Adwith Malpe', 'adwith.malpe@instructor.com'],
            ['Aggelos K. Katsaggelos', 'aggelos.k.katsaggelos@instructor.com'],
            ['Ahmad Varasteh', 'ahmad.varasteh@instructor.com'],
            ['Aije Egwaikhide', 'aije.egwaikhide@instructor.com'],
            ['Akos Ledeczi', 'akos.ledeczi@instructor.com'],
            ['Alan Lester', 'alan.lester@instructor.com'],
            ['Alan Paradise', 'alan.paradise@instructor.com'],
            ['Albert Glock', 'albert.glock@instructor.com'],
            ['Alex Aklson', 'alex.aklson@instructor.com'],
            ['Alex Bottle', 'alex.bottle@instructor.com'],
            ['Alex Cowan', 'alex.cowan@instructor.com'],
            ['Alex Fosdick', 'alex.fosdick@instructor.com'],
            ['Alex G.', 'alex.g@instructor.com'],
            ['Alex Mannella', 'alex.mannella@instructor.com'],
            ['Alex Parker', 'alex.parker@instructor.com'],
            ['Alex Tapscott', 'alex.tapscott@instructor.com'],
            ['Alexander Fred-Ojala', 'alexander.fred.ojala@instructor.com'],
            ['Alexander N. Hristov', 'alexander.n.hristov@instructor.com'],
            ['Alexander S. Kulikov', 'alexander.s.kulikov@instructor.com'],
            ['Alexander Waibel', 'alexander.waibel@instructor.com'],
            ['Alexandra Seidenstein', 'alexandra.seidenstein@instructor.com'],
            ['Alfredo Deza', 'alfredo.deza@instructor.com'],
            ['Alisa Acosta', 'alisa.acosta@instructor.com'],
            ['Allyson Pippin', 'allyson.pippin@instructor.com'],
            ['Alton Henley', 'alton.henley@instructor.com'],
            ['Alyssa Swanson', 'alyssa.swanson@instructor.com'],
            ['Amanda  Wang', 'amanda.wang@instructor.com'],
            ['Amanda C. Graham', 'amanda.c.graham@instructor.com'],
            ['Amarnath Gupta', 'amarnath.gupta@instructor.com'],
            ['Amber Gould', 'amber.gould@instructor.com'],
            ['Amirhossein Kiani', 'amirhossein.kiani@instructor.com'],
            ['Amit Navgire', 'amit.navgire@instructor.com'],
            ['Amit Yadav', 'amit.yadav@instructor.com'],
            ['Amy Brereton', 'amy.brereton@instructor.com'],
            ['Amy Moore', 'amy.moore@instructor.com'],
            ['Amy Norton', 'amy.norton@instructor.com'],
            ['Amy Webster', 'amy.webster@instructor.com'],
            ['Ana Nordberg', 'ana.nordberg@instructor.com'],
            ['Analytics Vidhya', 'analytics.vidhya@instructor.com'],
            ['Anand Padmanabhan', 'anand.padmanabhan@instructor.com'],
            ['Andrea C. Wade, Ph.D.', 'andrea.c.wade.ph.d@instructor.com'],
            ['Andrea Vitaletti', 'andrea.vitaletti@instructor.com'],
            ['Andrew D. Hilton', 'andrew.d.hilton@instructor.com'],
            ['Andrew Ng', 'andrew.ng@instructor.com'],
            ['Andrew Wu', 'andrew.wu@instructor.com'],
            ['Andrey Breslav', 'andrey.breslav@instructor.com'],
            ['Andy Friedland', 'andy.friedland@instructor.com'],
            ['Andy Lawrence', 'andy.lawrence@instructor.com'],
            ['Angela Wall', 'angela.wall@instructor.com'],
            ['Angelo Paolillo', 'angelo.paolillo@instructor.com'],
            ['Anh Le', 'anh.le@instructor.com'],
            ['Ania Kubow', 'ania.kubow@instructor.com'],
            ['Anita Raimondi', 'anita.raimondi@instructor.com'],
            ['Anju M Dominic', 'anju.m.dominic@instructor.com'],
            ['Anke Audenaert', 'anke.audenaert@instructor.com'],
            ['Ankit Singla', 'ankit.singla@instructor.com'],
            ['Ann Kovattil', 'ann.kovattil@instructor.com'],
            ['Anna Ball', 'anna.ball@instructor.com'],
            ['Anna Koop', 'anna.koop@instructor.com'],
            ['Anna Sfyrla', 'anna.sfyrla@instructor.com'],
            ['Annafederica Urbano', 'annafederica.urbano@instructor.com'],
            ['Annamaria Italiano', 'annamaria.italiano@instructor.com'],
            ['Anne Bracy', 'anne.bracy@instructor.com'],
            ['Anne Dougherty', 'anne.dougherty@instructor.com'],
            ['Anne Firth Murray', 'anne.firth.murray@instructor.com'],
            ['Anne M. Libby, PhD', 'anne.m.libby.phd@instructor.com'],
            ['Annemarie Zand Scholten', 'annemarie.zand.scholten@instructor.com'],
            ['Annette Philip', 'annette.philip@instructor.com'],
            ['Anshuman Singh', 'anshuman.singh@instructor.com'],
            ['Anthony J. Martin', 'anthony.j.martin@instructor.com'],
            ['Anthony Lehmann', 'anthony.lehmann@instructor.com'],
            ['Antje Barth', 'antje.barth@instructor.com'],
            ['Antoine Geissbuhler', 'antoine.geissbuhler@instructor.com'],
            ['Antonio Cangiano', 'antonio.cangiano@instructor.com'],
            ['Apostolos P. Fournaris', 'apostolos.p.fournaris@instructor.com'],
            ['Arabella MacPherson', 'arabella.macpherson@instructor.com'],
            ['Argyro Chatzopoulou', 'argyro.chatzopoulou@instructor.com'],
            ['Arimoro Olayinka Imisioluwa', 'arimoro.olayinka.imisioluwa@instructor.com'],
            ['Arnaud De Bruyn', 'arnaud.de.bruyn@instructor.com'],
            ['Artem Arutyunov', 'artem.arutyunov@instructor.com'],
            ['Arthur Salmon', 'arthur.salmon@instructor.com'],
            ['Aruba Education Services', 'aruba.education.services@instructor.com'],
            ['Aruna Chandran, MD, MPH', 'aruna.chandran.md.mph@instructor.com'],
            ['Arunachala Nadar Mada Kannan', 'arunachala.nadar.mada.kannan@instructor.com'],
            ['Ashish Dikshit', 'ashish.dikshit@instructor.com'],
            ['Ashish Khandelwal', 'ashish.khandelwal@instructor.com'],
            ['Ashwini S. Davison, M.D.', 'ashwini.s.davison.m.d@instructor.com'],
            ['Asja Kamenica', 'asja.kamenica@instructor.com'],
            ['Aspen Olmsted', 'aspen.olmsted@instructor.com'],
            ['Associate Professor Lawrence Ang', 'associate.professor.lawrence.ang@instructor.com'],
            ['Associate Professor Suseela Malakolunthu', 'associate.professor.suseela.malakolunthu@instructor.com'],
            ['Athanasia Lampraki', 'athanasia.lampraki@instructor.com'],
            ['Augustin Cacot', 'augustin.cacot@instructor.com'],
            ['Automation Anywhere, Inc.', 'automation.anywhere.inc@instructor.com'],
            ['Ayelet Sela', 'ayelet.sela@instructor.com'],
            ['Azim Hirjani', 'azim.hirjani@instructor.com'],
            ['Barbara Carminati', 'barbara.carminati@instructor.com'],
            ['Barbara E. Kahn', 'barbara.e.kahn@instructor.com'],
            ['Barbara Oakley', 'barbara.oakley@instructor.com'],
            ['Barry Nalebuff', 'barry.nalebuff@instructor.com'],
            ['Barsha Saha', 'barsha.saha@instructor.com'],
            ['Bart Smolders', 'bart.smolders@instructor.com'],
            ['Bart Van Zeghbroeck', 'bart.van.zeghbroeck@instructor.com'],
            ['Bassim Eledath', 'bassim.eledath@instructor.com'],
            ['Bastien Chopard', 'bastien.chopard@instructor.com'],
            ['Belinda Needham', 'belinda.needham@instructor.com'],
            ['Ben Langmead, PhD', 'ben.langmead.phd@instructor.com'],
            ['Ben Shaw', 'ben.shaw@instructor.com'],
            ['Ben Y B CHAN', 'ben.y.b.chan@instructor.com'],
            ['Benjamin Cowling (HKU)', 'benjamin.cowling.hku@instructor.com'],
            ['Benjamin Spriggs', 'benjamin.spriggs@instructor.com'],
            ['Bennett Shaywitz', 'bennett.shaywitz@instructor.com'],
            ['Bert Blocken', 'bert.blocken@instructor.com'],
            ['Beth Christie', 'beth.christie@instructor.com'],
            ['Bethany Hudnutt', 'bethany.hudnutt@instructor.com'],
            ['Bhramar Mukherjee', 'bhramar.mukherjee@instructor.com'],
            ['Bhushan Jayarao', 'bhushan.jayarao@instructor.com'],
            ['Bill Adair', 'bill.adair@instructor.com'],
            ['Bill Bailey, PhD', 'bill.bailey.phd@instructor.com'],
            ['Bill Howe', 'bill.howe@instructor.com'],
            ['Bill Millar', 'bill.millar@instructor.com'],
            ['Bill Miller', 'bill.miller@instructor.com'],
            ['Bina Ramamurthy', 'bina.ramamurthy@instructor.com'],
            ['Blaine Sundrud', 'blaine.sundrud@instructor.com'],
            ['Board Infinity', 'board.infinity@instructor.com'],
            ['Bobby Schnabel', 'bobby.schnabel@instructor.com'],
            ['Bora Uyumazturk', 'bora.uyumazturk@instructor.com'],
            ['Bowon Kim', 'bowon.kim@instructor.com'],
            ['Brady T. West', 'brady.t.west@instructor.com'],
            ['Brandon Armstrong', 'brandon.armstrong@instructor.com'],
            ['Brandon Krakowsky', 'brandon.krakowsky@instructor.com'],
            ['Brandon Larkin', 'brandon.larkin@instructor.com'],
            ['Brenda Gunderson', 'brenda.gunderson@instructor.com'],
            ['Brenda J. Allen', 'brenda.j.allen@instructor.com'],
            ['Brendan McKeown', 'brendan.mckeown@instructor.com'],
            ['Brent Summers', 'brent.summers@instructor.com'],
            ['Brian Broll', 'brian.broll@instructor.com'],
            ['Brian Buechel', 'brian.buechel@instructor.com'],
            ['Brian Caffo, PhD', 'brian.caffo.phd@instructor.com'],
            ['Brian J Bushee', 'brian.j.bushee@instructor.com'],
            ['Brian Nick', 'brian.nick@instructor.com'],
            ['Brian Paciotti', 'brian.paciotti@instructor.com'],
            ['Brian Winn', 'brian.winn@instructor.com'],
            ['Brian Zaharatos', 'brian.zaharatos@instructor.com'],
            ['Briana Mezuk', 'briana.mezuk@instructor.com'],
            ['Brooke Anderson', 'brooke.anderson@instructor.com'],
            ['Brooke Wenig', 'brooke.wenig@instructor.com'],
            ['Bruce Branham', 'bruce.branham@instructor.com'],
            ['Bruce Montgomery, PhD, PMP', 'bruce.montgomery.phd.pmp@instructor.com'],
            ['CJ Taylor', 'cj.taylor@instructor.com'],
            ['Cade Massey', 'cade.massey@instructor.com'],
            ['Cam Harvey', 'cam.harvey@instructor.com'],
            ['Cameron Dodd', 'cameron.dodd@instructor.com'],
            ['Camille Funk', 'camille.funk@instructor.com'],
            ['Carlo Ghezzi', 'carlo.ghezzi@instructor.com'],
            ['Carlos Buskey', 'carlos.buskey@instructor.com'],
            ['Carlos Guestrin', 'carlos.guestrin@instructor.com'],
            ['Caroline Samer', 'caroline.samer@instructor.com'],
            ['Carrie Wright, PhD', 'carrie.wright.phd@instructor.com'],
            ['Catalin Popa', 'catalin.popa@instructor.com'],
            ['Catherine Heymans', 'catherine.heymans@instructor.com'],
            ['Center for Academic Innovation Experts', 'center.for.academic.innovation.experts@instructor.com'],
            ['Chad Dechow', 'chad.dechow@instructor.com'],
            ['Chaitra Deshpande', 'chaitra.deshpande@instructor.com'],
            ['Chalece DeLaCoudray', 'chalece.delacoudray@instructor.com'],
            ['Chan-Byoung Chae', 'chan.byoung.chae@instructor.com'],
            ['Chancellor Thomas Pascale', 'chancellor.thomas.pascale@instructor.com'],
            ['Charles Bamforth', 'charles.bamforth@instructor.com'],
            ['Charles Cockell', 'charles.cockell@instructor.com'],
            ['Charles Harry', 'charles.harry@instructor.com'],
            ['Charles Ivan Niswander II', 'charles.ivan.niswander.ii@instructor.com'],
            ['Charles Newell', 'charles.newell@instructor.com'],
            ['Charles Russell Severance', 'charles.russell.severance@instructor.com'],
            ['Charles W. Clark', 'charles.w.clark@instructor.com'],
            ['Charlie Nuttelman', 'charlie.nuttelman@instructor.com'],
            ['Charmaine Williams', 'charmaine.williams@instructor.com'],
            ['Check Point Software Technologies, Ltd.', 'check.point.software.technologies.ltd@instructor.com'],
            ['ChengXiang Zhai', 'chengxiang.zhai@instructor.com'],
            ['Cheong Siew Ann', 'cheong.siew.ann@instructor.com'],
            ['Chiara Succi', 'chiara.succi@instructor.com'],
            ['Chirag Shah', 'chirag.shah@instructor.com'],
            ['Chris Caillouet', 'chris.caillouet@instructor.com'],
            ['Chris Fregly', 'chris.fregly@instructor.com'],
            ['Chris Impey', 'chris.impey@instructor.com'],
            ['Chris Koehler', 'chris.koehler@instructor.com'],
            ['Chris McCain', 'chris.mccain@instructor.com'],
            ['Chris Myers', 'chris.myers@instructor.com'],
            ['Chris Reed', 'chris.reed@instructor.com'],
            ['Chris Wright', 'chris.wright@instructor.com'],
            ['Christelle Borel', 'christelle.borel@instructor.com'],
            ['Christiaan Heij', 'christiaan.heij@instructor.com'],
            ['Christina Scherrer, PhD', 'christina.scherrer.phd@instructor.com'],
            ['Christine Alvarado', 'christine.alvarado@instructor.com'],
            ['Christopher Boone', 'christopher.boone@instructor.com'],
            ['Christopher Brooks', 'christopher.brooks@instructor.com'],
            ['Christopher Chao', 'christopher.chao@instructor.com'],
            ['Christopher D. Ittner', 'christopher.d.ittner@instructor.com'],
            ['Christopher Geczy', 'christopher.geczy@instructor.com'],
            ['Christopher Giardina', 'christopher.giardina@instructor.com'],
            ['Christopher Hassall', 'christopher.hassall@instructor.com'],
            ['Christopher Lee Stevens', 'christopher.lee.stevens@instructor.com'],
            ['Christopher Millard', 'christopher.millard@instructor.com'],
            ['Christopher Slobogin', 'christopher.slobogin@instructor.com'],
            ['Christy Bozic, PhD, PMP', 'christy.bozic.phd.pmp@instructor.com'],
            ['Cindy  Carbajal', 'cindy.carbajal@instructor.com'],
            ['Cinny Buys', 'cinny.buys@instructor.com'],
            ['Cisco Learning & Certifications', 'cisco.learning.certifications@instructor.com'],
            ['Claire McDonnell', 'claire.mcdonnell@instructor.com'],
            ['Claudia Carrone', 'claudia.carrone@instructor.com'],
            ['Claudia Useche', 'claudia.useche@instructor.com'],
            ['Cleopatra Caldwell', 'cleopatra.caldwell@instructor.com'],
            ['Click Start', 'click.start@instructor.com'],
            ['Clifford B Anderson', 'clifford.b.anderson@instructor.com'],
            ['Clifford Lampe', 'clifford.lampe@instructor.com'],
            ['Colleen van Lent, Ph.D.', 'colleen.van.lent.ph.d@instructor.com'],
            ['Collin Paschall', 'collin.paschall@instructor.com'],
            ['CompTIA Fast Track to Tech', 'comptia.fast.track.to.tech@instructor.com'],
            ['Connie B. Scanga, PhD', 'connie.b.scanga.phd@instructor.com'],
            ['Conor Murphy', 'conor.murphy@instructor.com'],
            ['Corey Leong', 'corey.leong@instructor.com'],
            ['Coursera QA Team', 'coursera.qa.team@instructor.com'],
            ['Courtney Kissler', 'courtney.kissler@instructor.com'],
            ['Craig Smith', 'craig.smith@instructor.com'],
            ['Craig Wright', 'craig.wright@instructor.com'],
            ['Cris LaPierre', 'cris.lapierre@instructor.com'],
            ['Dae-Sik Hong', 'dae.sik.hong@instructor.com'],
            ['Dan  Grossman', 'dan.grossman@instructor.com'],
            ['Dan Boneh', 'dan.boneh@instructor.com'],
            ['Daniel Boley', 'daniel.boley@instructor.com'],
            ['Daniel C. Yeomans', 'daniel.c.yeomans@instructor.com'],
            ['Daniel E. Koditschek', 'daniel.e.koditschek@instructor.com'],
            ['Daniel Egger', 'daniel.egger@instructor.com'],
            ['Daniel Frank', 'daniel.frank@instructor.com'],
            ['Daniel J. Pesut, Ph.D., RN, FAAN', 'daniel.j.pesut.ph.d.rn.faan@instructor.com'],
            ['Daniel Lee', 'daniel.lee@instructor.com'],
            ['Daniel M Kane', 'daniel.m.kane@instructor.com'],
            ['Daniel Niazov', 'daniel.niazov@instructor.com'],
            ['Daniel Randall', 'daniel.randall@instructor.com'],
            ['Daniel Romero', 'daniel.romero@instructor.com'],
            ['Daniel Walkes', 'daniel.walkes@instructor.com'],
            ['Danilo Oliveira Vaz', 'danilo.oliveira.vaz@instructor.com'],
            ['Daphne Koller', 'daphne.koller@instructor.com'],
            ['Dave Hatter', 'dave.hatter@instructor.com'],
            ['Dave Reay', 'dave.reay@instructor.com'],
            ['David Adamson', 'david.adamson@instructor.com'],
            ['David Archer', 'david.archer@instructor.com'],
            ['David Carlson', 'david.carlson@instructor.com'],
            ['David Chesney', 'david.chesney@instructor.com'],
            ['David Cook, PhD', 'david.cook.phd@instructor.com'],
            ['David Dalsveen', 'david.dalsveen@instructor.com'],
            ['David Dye', 'david.dye@instructor.com'],
            ['David Easdown', 'david.easdown@instructor.com'],
            ['David Gomez-Cabrero', 'david.gomez.cabrero@instructor.com'],
            ['David Hik', 'david.hik@instructor.com'],
            ['David Magnus', 'david.magnus@instructor.com'],
            ['David Musto', 'david.musto@instructor.com'],
            ['David Sluiter', 'david.sluiter@instructor.com'],
            ['David Torgerson', 'david.torgerson@instructor.com'],
            ['David Underwood', 'david.underwood@instructor.com'],
            ['David Van Kleeck', 'david.van.kleeck@instructor.com'],
            ['David Wentzlaff', 'david.wentzlaff@instructor.com'],
            ['David van Klaveren', 'david.van.klaveren@instructor.com'],
            ['Davide Nadali', 'davide.nadali@instructor.com'],
            ['Dean Savovic', 'dean.savovic@instructor.com'],
            ['Dee Dee Collette', 'dee.dee.collette@instructor.com'],
            ['Delphine Sangotokun', 'delphine.sangotokun@instructor.com'],
            ['Denise Duffy', 'denise.duffy@instructor.com'],
            ['Dennis Davenport', 'dennis.davenport@instructor.com'],
            ['Dennis Fok', 'dennis.fok@instructor.com'],
            ['Deondra Rose, PhD', 'deondra.rose.phd@instructor.com'],
            ['Derek Meng', 'derek.meng@instructor.com'],
            ['Derek Parsons', 'derek.parsons@instructor.com'],
            ['Desiree\' Abbott', 'desiree.abbott@instructor.com'],
            ['Detlef Koschny', 'detlef.koschny@instructor.com'],
            ['Develop with Dell', 'develop.with.dell@instructor.com'],
            ['Dhruv Bhate', 'dhruv.bhate@instructor.com'],
            ['Di Wu', 'di.wu@instructor.com'],
            ['Diana Bilimoria, PhD', 'diana.bilimoria.phd@instructor.com'],
            ['Diane Davidson', 'diane.davidson@instructor.com'],
            ['Dick van Dijk', 'dick.van.dijk@instructor.com'],
            ['Dimitra Kamarinou', 'dimitra.kamarinou@instructor.com'],
            ['Diptesh Ghosh', 'diptesh.ghosh@instructor.com'],
            ['Dirk Effenberger', 'dirk.effenberger@instructor.com'],
            ['Dmitrii Suchkov', 'dmitrii.suchkov@instructor.com'],
            ['Dmitry Vinnik', 'dmitry.vinnik@instructor.com'],
            ['Domine Leenaerts', 'domine.leenaerts@instructor.com'],
            ['Dominic Tanzillo', 'dominic.tanzillo@instructor.com'],
            ['Dominique Moser', 'dominique.moser@instructor.com'],
            ['Don Boyes', 'don.boyes@instructor.com'],
            ['Don Huesman', 'don.huesman@instructor.com'],
            ['Don Noxon', 'don.noxon@instructor.com'],
            ['Don Patterson', 'don.patterson@instructor.com'],
            ['Don Tapscott', 'don.tapscott@instructor.com'],
            ['Donald Hornstein', 'donald.hornstein@instructor.com'],
            ['Dong-Yeun Koh', 'dong.yeun.koh@instructor.com'],
            ['Dora Hrvoj', 'dora.hrvoj@instructor.com'],
            ['Doug Berman', 'doug.berman@instructor.com'],
            ['Douglas B. Laney', 'douglas.b.laney@instructor.com'],
            ['Douglas C. Montgomery', 'douglas.c.montgomery@instructor.com'],
            ['Dr Areti Manataki', 'dr.areti.manataki@instructor.com'],
            ['Dr Dan Plesch, SOAS University of London', 'dr.dan.plesch.soas.university.of.london@instructor.com'],
            ['Dr David Carmel', 'dr.david.carmel@instructor.com'],
            ['Dr Edward Anstead', 'dr.edward.anstead@instructor.com'],
            ['Dr Eileen Kennedy', 'dr.eileen.kennedy@instructor.com'],
            ['Dr Elizabeth  J.  Angstmann', 'dr.elizabeth.j.angstmann@instructor.com'],
            ['Dr Frances Wong', 'dr.frances.wong@instructor.com'],
            ['Dr Giorgio Locatelli', 'dr.giorgio.locatelli@instructor.com'],
            ['Dr Ian  Faulconbridge', 'dr.ian.faulconbridge@instructor.com'],
            ['Dr J Adam Carter', 'dr.j.adam.carter@instructor.com'],
            ['Dr J. Simon Rofe, SOAS, University of London', 'dr.j.simon.rofe.soas.university.of.london@instructor.com'],
            ['Dr James Ohene-Djan', 'dr.james.ohene.djan@instructor.com'],
            ['Dr Jonathan Ward', 'dr.jonathan.ward@instructor.com'],
            ['Dr Kate Devlin', 'dr.kate.devlin@instructor.com'],
            ['Dr Kenny Smith', 'dr.kenny.smith@instructor.com'],
            ['Dr Kevin Webster', 'dr.kevin.webster@instructor.com'],
            ['Dr Leone Leonida', 'dr.leone.leonida@instructor.com'],
            ['Dr Louise Connelly', 'dr.louise.connelly@instructor.com'],
            ['Dr Mark Sprevak', 'dr.mark.sprevak@instructor.com'],
            ['Dr Mary Ann Weitnauer', 'dr.mary.ann.weitnauer@instructor.com'],
            ['Dr Mary Kalantzis', 'dr.mary.kalantzis@instructor.com'],
            ['Dr Matthew Yee-King', 'dr.matthew.yee.king@instructor.com'],
            ['Dr Michele Curioni', 'dr.michele.curioni@instructor.com'],
            ['Dr Mick Grierson', 'dr.mick.grierson@instructor.com'],
            ['Dr Mike Robinson', 'dr.mike.robinson@instructor.com'],
            ['Dr Mike Ryan', 'dr.mike.ryan@instructor.com'],
            ['Dr Mog Stapleton', 'dr.mog.stapleton@instructor.com'],
            ['Dr Nancy Weitz', 'dr.nancy.weitz@instructor.com'],
            ['Dr Nick Stevens, BSc PhD', 'dr.nick.stevens.bsc.phd@instructor.com'],
            ['Dr Omar Sharaf', 'dr.omar.sharaf@instructor.com'],
            ['Dr Orestis Palermos', 'dr.orestis.palermos@instructor.com'],
            ['Dr Peggy Series', 'dr.peggy.series@instructor.com'],
            ['Dr Prashan S. M. Karunaratne', 'dr.prashan.s.m.karunaratne@instructor.com'],
            ['Dr Rafael Papallas', 'dr.rafael.papallas@instructor.com'],
            ['Dr Robert Lindsay', 'dr.robert.lindsay@instructor.com'],
            ['Dr Simon Katan', 'dr.simon.katan@instructor.com'],
            ['Dr Susan Winks', 'dr.susan.winks@instructor.com'],
            ['Dr William Cope', 'dr.william.cope@instructor.com'],
            ['Dr Yenn Lee', 'dr.yenn.lee@instructor.com'],
            ['Dr.  Christopher J.  Cramer', 'dr.christopher.j.cramer@instructor.com'],
            ['Dr.  Dave Ward', 'dr.dave.ward@instructor.com'],
            ['Dr.  David W. Johnston', 'dr.david.w.johnston@instructor.com'],
            ['Dr.  Jessica L. Metcalf', 'dr.jessica.l.metcalf@instructor.com'],
            ['Dr.  Margaret Anne Schedel', 'dr.margaret.anne.schedel@instructor.com'],
            ['Dr. Alasdair Richmond', 'dr.alasdair.richmond@instructor.com'],
            ['Dr. Allan Hazlett', 'dr.allan.hazlett@instructor.com'],
            ['Dr. Allison Soult', 'dr.allison.soult@instructor.com'],
            ['Dr. Armend Tahirsylaj', 'dr.armend.tahirsylaj@instructor.com'],
            ['Dr. Bernadett Kiss', 'dr.bernadett.kiss@instructor.com'],
            ['Dr. Bonnie H. Ferri', 'dr.bonnie.h.ferri@instructor.com'],
            ['Dr. Brent Hecht', 'dr.brent.hecht@instructor.com'],
            ['Dr. Bruce W Jentleson', 'dr.bruce.w.jentleson@instructor.com'],
            ['Dr. Carleton Coffrin', 'dr.carleton.coffrin@instructor.com'],
            ['Dr. Chris Brooks', 'dr.chris.brooks@instructor.com'],
            ['Dr. Darrell Velegol', 'dr.darrell.velegol@instructor.com'],
            ['Dr. Dominic William Massaro', 'dr.dominic.william.massaro@instructor.com'],
            ['Dr. Douglas C. Schmidt', 'dr.douglas.c.schmidt@instructor.com'],
            ['Dr. Dragan Maksimovic', 'dr.dragan.maksimovic@instructor.com'],
            ['Dr. Edward G. Amoroso', 'dr.edward.g.amoroso@instructor.com'],
            ['Dr. Eileen Herrstrom', 'dr.eileen.herrstrom@instructor.com'],
            ['Dr. Fortem Mbah', 'dr.fortem.mbah@instructor.com'],
            ['Dr. Gene E. Robinson', 'dr.gene.e.robinson@instructor.com'],
            ['Dr. Helen Toxopeus', 'dr.helen.toxopeus@instructor.com'],
            ['Dr. Humayun Zafar, CEH, CISM, CRISC, PCIP', 'dr.humayun.zafar.ceh.cism.crisc.pcip@instructor.com'],
            ['Dr. Jack V. Matson', 'dr.jack.v.matson@instructor.com'],
            ['Dr. Jacquie Hutchinson', 'dr.jacquie.hutchinson@instructor.com'],
            ['Dr. James Fricton, DDS, MS', 'dr.james.fricton.dds.ms@instructor.com'],
            ['Dr. James V. Green', 'dr.james.v.green@instructor.com'],
            ['Dr. Jennifer Coy', 'dr.jennifer.coy@instructor.com'],
            ['Dr. Jerry Roth', 'dr.jerry.roth@instructor.com'],
            ['Dr. John D. Halamka, M.D., M.S.', 'dr.john.d.halamka.m.d.m.s@instructor.com'],
            ['Dr. Jonathan Tomkin', 'dr.jonathan.tomkin@instructor.com'],
            ['Dr. Joyelle Harris', 'dr.joyelle.harris@instructor.com'],
            ['Dr. Jules White', 'dr.jules.white@instructor.com'],
            ['Dr. Julie L. Johnson', 'dr.julie.l.johnson@instructor.com'],
            ['Dr. Katherine R. Amato', 'dr.katherine.r.amato@instructor.com'],
            ['Dr. Kathryn W. Jablokow', 'dr.kathryn.w.jablokow@instructor.com'],
            ['Dr. Kathryn Wingate', 'dr.kathryn.wingate@instructor.com'],
            ['Dr. Keith Devlin', 'dr.keith.devlin@instructor.com'],
            ['Dr. Kim Woodrum', 'dr.kim.woodrum@instructor.com'],
            ['Dr. Matthew Chrisman', 'dr.matthew.chrisman@instructor.com'],
            ['Dr. Maya Evenden', 'dr.maya.evenden@instructor.com'],
            ['Dr. Mohamed Noor', 'dr.mohamed.noor@instructor.com'],
            ['Dr. Nick Feamster', 'dr.nick.feamster@instructor.com'],
            ['Dr. Nick Weise', 'dr.nick.weise@instructor.com'],
            ['Dr. Petra Bonfert-Taylor', 'dr.petra.bonfert.taylor@instructor.com'],
            ['Dr. Philip Roberts', 'dr.philip.roberts@instructor.com'],
            ['Dr. Pooja', 'dr.pooja@instructor.com'],
            ['Dr. Quentin McAndrew', 'dr.quentin.mcandrew@instructor.com'],
            ['Dr. Robert Allen Robinson, Jr.', 'dr.robert.allen.robinson.jr@instructor.com'],
            ['Dr. Robert Erickson', 'dr.robert.erickson@instructor.com'],
            ['Dr. Rosa I. Arriaga', 'dr.rosa.i.arriaga@instructor.com'],
            ['Dr. Srijith Rajamohan', 'dr.srijith.rajamohan@instructor.com'],
            ['Dr. Stephen Marshak', 'dr.stephen.marshak@instructor.com'],
            ['Dr. Stephen Mayfield', 'dr.stephen.mayfield@instructor.com'],
            ['Dr. Suilin Lavelle', 'dr.suilin.lavelle@instructor.com'],
            ['Dr. Surya Kalidindi', 'dr.surya.kalidindi@instructor.com'],
            ['Dr. Terrence Sejnowski', 'dr.terrence.sejnowski@instructor.com'],
            ['Dr. Terry A. Matilsky', 'dr.terry.a.matilsky@instructor.com'],
            ['Dr. Thomas J. Mierzwa', 'dr.thomas.j.mierzwa@instructor.com'],
            ['Dr. Tim "Dr. T" Chamillard', 'dr.tim.dr.t.chamillard@instructor.com'],
            ['Dr. Tom  Morley', 'dr.tom.morley@instructor.com'],
            ['Dr. Uri Hangorsky', 'dr.uri.hangorsky@instructor.com'],
            ['Dr. Victor Galitski', 'dr.victor.galitski@instructor.com'],
            ['Dr. Wayne Whiteman, PE', 'dr.wayne.whiteman.pe@instructor.com'],
            ['Dr. Yuliya Voytenko Palgan', 'dr.yuliya.voytenko.palgan@instructor.com'],
            ['Drew Wilson', 'drew.wilson@instructor.com'],
            ['Duane Szafron', 'duane.szafron@instructor.com'],
            ['Dumitru Bogdan PRELIPCEAN', 'dumitru.bogdan.prelipcean@instructor.com'],
            ['Dylan Sheffer', 'dylan.sheffer@instructor.com'],
            ['E. Geoffrey Love', 'e.geoffrey.love@instructor.com'],
            ['Ebony Williams', 'ebony.williams@instructor.com'],
            ['Eda Zhou', 'eda.zhou@instructor.com'],
            ['Eddie Stern', 'eddie.stern@instructor.com'],
            ['Eddy Shyu', 'eddy.shyu@instructor.com'],
            ['Eder John Scheid', 'eder.john.scheid@instructor.com'],
            ['Edmond Mathez, Ph.D.', 'edmond.mathez.ph.d@instructor.com'],
            ['Edmund Player', 'edmund.player@instructor.com'],
            ['Edward Chow', 'edward.chow@instructor.com'],
            ['Edward Falzon', 'edward.falzon@instructor.com'],
            ['Elena Brewer', 'elena.brewer@instructor.com'],
            ['Elena Ferrari', 'elena.ferrari@instructor.com'],
            ['Elena Sanina', 'elena.sanina@instructor.com'],
            ['Elinor Mason', 'elinor.mason@instructor.com'],
            ['Elise Deitrick', 'elise.deitrick@instructor.com'],
            ['Elizabeth Gerber', 'elizabeth.gerber@instructor.com'],
            ['Ellen  VanOosten, PhD', 'ellen.vanoosten.phd@instructor.com'],
            ['Elliott Spaeth', 'elliott.spaeth@instructor.com'],
            ['Emanuel Demetrescu', 'emanuel.demetrescu@instructor.com'],
            ['Emanuela Colombo', 'emanuela.colombo@instructor.com'],
            ['Emanuele Della Valle', 'emanuele.della.valle@instructor.com'],
            ['Emiel van Loon', 'emiel.van.loon@instructor.com'],
            ['Emily Fox', 'emily.fox@instructor.com'],
            ['Emily Pressman', 'emily.pressman@instructor.com'],
            ['Emma Freeman', 'emma.freeman@instructor.com'],
            ['Emma Irving', 'emma.irving@instructor.com'],
            ['Emma Martin', 'emma.martin@instructor.com'],
            ['Emmanuel Segui', 'emmanuel.segui@instructor.com'],
            ['Enrique Barra', 'enrique.barra@instructor.com'],
            ['Eric Barrette', 'eric.barrette@instructor.com'],
            ['Eric Bradlow', 'eric.bradlow@instructor.com'],
            ['Eric Howard', 'eric.howard@instructor.com'],
            ['Eric Muller', 'eric.muller@instructor.com'],
            ['Eric Poquillon', 'eric.poquillon@instructor.com'],
            ['Eric Zelikman', 'eric.zelikman@instructor.com'],
            ['Erik Adli', 'erik.adli@instructor.com'],
            ['Erik Herman', 'erik.herman@instructor.com'],
            ['Erik Kole', 'erik.kole@instructor.com'],
            ['Erika Warnatzsch Thompson', 'erika.warnatzsch.thompson@instructor.com'],
            ['Erin Byrne', 'erin.byrne@instructor.com'],
            ['Erin O\'Hara-Leslie', 'erin.o.hara.leslie@instructor.com'],
            ['Erin Wilson', 'erin.wilson@instructor.com'],
            ['Erjan Gavalji', 'erjan.gavalji@instructor.com'],
            ['Ester van der Voet', 'ester.van.der.voet@instructor.com'],
            ['Esther Quaedackers', 'esther.quaedackers@instructor.com'],
            ['Eva Garen', 'eva.garen@instructor.com'],
            ['Evan Bergman', 'evan.bergman@instructor.com'],
            ['Evan Fingerman', 'evan.fingerman@instructor.com'],
            ['Evangelia Katsikea', 'evangelia.katsikea@instructor.com'],
            ['Evert Stamhuis', 'evert.stamhuis@instructor.com'],
            ['Ewout W. Steyerberg', 'ewout.w.steyerberg@instructor.com'],
            ['F. Perry Wilson', 'f.perry.wilson@instructor.com'],
            ['Fabian Garcia Pastor', 'fabian.garcia.pastor@instructor.com'],
            ['Fadi Hirzalla', 'fadi.hirzalla@instructor.com'],
            ['Fang Yang', 'fang.yang@instructor.com'],
            ['Farhoud Hosseinpour', 'farhoud.hosseinpour@instructor.com'],
            ['Farshida Zafar', 'farshida.zafar@instructor.com'],
            ['Federico Ast', 'federico.ast@instructor.com'],
            ['Filippos Filippidis', 'filippos.filippidis@instructor.com'],
            ['Flemming Jappe Frandsen', 'flemming.jappe.frandsen@instructor.com'],
            ['Fractal Analytics', 'fractal.analytics@instructor.com'],
            ['Francesca Curbis', 'francesca.curbis@instructor.com'],
            ['Francine Gresnigt', 'francine.gresnigt@instructor.com'],
            ['Frederick W. Mayer', 'frederick.w.mayer@instructor.com'],
            ['Gabriel M. Leung (HKU)', 'gabriel.m.leung.hku@instructor.com'],
            ['Gabriela de Queiroz', 'gabriela.de.queiroz@instructor.com'],
            ['Gabriella A. Varga', 'gabriella.a.varga@instructor.com'],
            ['Gabrielle Fitzgerald', 'gabrielle.fitzgerald@instructor.com'],
            ['Galina Toteva', 'galina.toteva@instructor.com'],
            ['Gang Qu', 'gang.qu@instructor.com'],
            ['Ganz Chockalingam', 'ganz.chockalingam@instructor.com'],
            ['Garvin Percy DIAS', 'garvin.percy.dias@instructor.com'],
            ['Gary Hecht, Ph.D.', 'gary.hecht.ph.d@instructor.com'],
            ['Gay E Canough', 'gay.e.canough@instructor.com'],
            ['Gayle Allard', 'gayle.allard@instructor.com'],
            ['Genevieve M. Lipp', 'genevieve.m.lipp@instructor.com'],
            ['Geoff Ladwig', 'geoff.ladwig@instructor.com'],
            ['George Kapetanios', 'george.kapetanios@instructor.com'],
            ['Gerald Balekaki', 'gerald.balekaki@instructor.com'],
            ['Gerben Moerman', 'gerben.moerman@instructor.com'],
            ['Gideon OZIK', 'gideon.ozik@instructor.com'],
            ['Gies College of Business, University of Illinois', 'gies.college.of.business.university.of.illinois@instructor.com'],
            ['Gilbert Nyaga', 'gilbert.nyaga@instructor.com'],
            ['Giulia Pinzauti', 'giulia.pinzauti@instructor.com'],
            ['Giuliano M. Dragone', 'giuliano.m.dragone@instructor.com'],
            ['Giulio Magli', 'giulio.magli@instructor.com'],
            ['Glenn M. Fox', 'glenn.m.fox@instructor.com'],
            ['Glenn Wilcox', 'glenn.wilcox@instructor.com'],
            ['Goodwill Academy', 'goodwill.academy@instructor.com'],
            ['Google', 'google@instructor.com'],
            ['Google Career Certificates', 'google.career.certificates@instructor.com'],
            ['Google Cloud Training', 'google.cloud.training@instructor.com'],
            ['Gopesh Anand', 'gopesh.anand@instructor.com'],
            ['Gordon', 'gordon@instructor.com'],
            ['Gordon Yu', 'gordon.yu@instructor.com'],
            ['Govind Acharya', 'govind.acharya@instructor.com'],
            ['Graham Cunningham', 'graham.cunningham@instructor.com'],
            ['Greg Roth', 'greg.roth@instructor.com'],
            ['Greg Williams', 'greg.williams@instructor.com'],
            ['Gregory Plett', 'gregory.plett@instructor.com'],
            ['Gregory Wiles, PhD', 'gregory.wiles.phd@instructor.com'],
            ['Guan Yi (HKU)', 'guan.yi.hku@instructor.com'],
            ['Guenter W. Hein', 'guenter.w.hein@instructor.com'],
            ['Guenther Walther', 'guenther.walther@instructor.com'],
            ['Guillermo Sapiro', 'guillermo.sapiro@instructor.com'],
            ['Gunther Fleerackers', 'gunther.fleerackers@instructor.com'],
            ['Guy Fletcher', 'guy.fletcher@instructor.com'],
            ['H.V. Jagadish', 'h.v.jagadish@instructor.com'],
            ['Hadeel Sleem', 'hadeel.sleem@instructor.com'],
            ['Hadi H. K. Kharrazi, MD, Ph.D', 'hadi.h.k.kharrazi.md.ph.d@instructor.com'],
            ['Haiyi Zhu', 'haiyi.zhu@instructor.com'],
            ['Haley Axelrod', 'haley.axelrod@instructor.com'],
            ['Hanspeter Schaub', 'hanspeter.schaub@instructor.com'],
            ['Harald Heubaum', 'harald.heubaum@instructor.com'],
            ['Harald Winkler', 'harald.winkler@instructor.com'],
            ['Harinath Garudadri', 'harinath.garudadri@instructor.com'],
            ['Harold P. Lehmann, MD, Ph.D.', 'harold.p.lehmann.md.ph.d@instructor.com'],
            ['Harrison Kong', 'harrison.kong@instructor.com'],
            ['Hayden Noel', 'hayden.noel@instructor.com'],
            ['Heather Gorr', 'heather.gorr@instructor.com'],
            ['Heidi Barker', 'heidi.barker@instructor.com'],
            ['Helen Baghdoyan, Ph.D.', 'helen.baghdoyan.ph.d@instructor.com'],
            ['Helen Tibbo', 'helen.tibbo@instructor.com'],
            ['Henri Laurie', 'henri.laurie@instructor.com'],
            ['Henry Byorum', 'henry.byorum@instructor.com'],
            ['Herbert J. Mattord, Ph.D., CISM, CISSP, CDP', 'herbert.j.mattord.ph.d.cism.cissp.cdp@instructor.com'],
            ['Herbert Lee', 'herbert.lee@instructor.com'],
            ['Hima Vasudevan', 'hima.vasudevan@instructor.com'],
            ['Hori Tsuneki', 'hori.tsuneki@instructor.com'],
            ['Howard Poston', 'howard.poston@instructor.com'],
            ['Hunter Whitney', 'hunter.whitney@instructor.com'],
            ['Hussam El Aassar', 'hussam.el.aassar@instructor.com'],
            ['IBM Skills Network Team', 'ibm.skills.network.team@instructor.com'],
            ['Ian Harris', 'ian.harris@instructor.com'],
            ['Ian Shapiro', 'ian.shapiro@instructor.com'],
            ['Ian Walden', 'ian.walden@instructor.com'],
            ['Ibrahim Odeh, Ph.D., MBA', 'ibrahim.odeh.ph.d.mba@instructor.com'],
            ['Idris Guessous', 'idris.guessous@instructor.com'],
            ['Igor Halperin', 'igor.halperin@instructor.com'],
            ['Ilja Rasin', 'ilja.rasin@instructor.com'],
            ['Ilkay Altintas', 'ilkay.altintas@instructor.com'],
            ['Ilya Grinberg', 'ilya.grinberg@instructor.com'],
            ['Ines Alves', 'ines.alves@instructor.com'],
            ['Inez Zwetsloot', 'inez.zwetsloot@instructor.com'],
            ['Ira "Ike" Levine', 'ira.ike.levine@instructor.com'],
            ['Ira Pohl', 'ira.pohl@instructor.com'],
            ['Isaac Bruss', 'isaac.bruss@instructor.com'],
            ['Ittai Bar-Siman-Tov', 'ittai.bar.siman.tov@instructor.com'],
            ['Ivan Wanis Ruiz', 'ivan.wanis.ruiz@instructor.com'],
            ['Iwona Maciejowska', 'iwona.maciejowska@instructor.com'],
            ['JEREMY NILMEIER', 'jeremy.nilmeier@instructor.com'],
            ['Jack Farmer', 'jack.farmer@instructor.com'],
            ['Jack Goncalo', 'jack.goncalo@instructor.com'],
            ['Jack Noble', 'jack.noble@instructor.com'],
            ['Jack Sullivan', 'jack.sullivan@instructor.com'],
            ['Jacob Horne', 'jacob.horne@instructor.com'],
            ['Jacob O. Wobbrock', 'jacob.o.wobbrock@instructor.com'],
            ['Jacob Pritt', 'jacob.pritt@instructor.com'],
            ['Jagat Sesh Challa', 'jagat.sesh.challa@instructor.com'],
            ['Jahangir Karimi', 'jahangir.karimi@instructor.com'],
            ['Jake Lever', 'jake.lever@instructor.com'],
            ['James Bird', 'james.bird@instructor.com'],
            ['James D. Van De Ven, PhD', 'james.d.van.de.ven.phd@instructor.com'],
            ['James Dalton', 'james.dalton@instructor.com'],
            ['James Dunn', 'james.dunn@instructor.com'],
            ['James Kit Hon Tsoi', 'james.kit.hon.tsoi@instructor.com'],
            ['James Milke, PhD', 'james.milke.phd@instructor.com'],
            ['James Wagner', 'james.wagner@instructor.com'],
            ['James Won-Ki HONG', 'james.won.ki.hong@instructor.com'],
            ['James Z. Lee', 'james.z.lee@instructor.com'],
            ['James Zweighaft', 'james.zweighaft@instructor.com'],
            ['Jan Niehues', 'jan.niehues@instructor.com'],
            ['Jan Smits', 'jan.smits@instructor.com'],
            ['Jana Schaich Borg', 'jana.schaich.borg@instructor.com'],
            ['Jane Wall', 'jane.wall@instructor.com'],
            ['Jang-Ung Park', 'jang.ung.park@instructor.com'],
            ['Janice Sanders', 'janice.sanders@instructor.com'],
            ['Jason A. Roy, Ph.D.', 'jason.a.roy.ph.d@instructor.com'],
            ['Jason Chan', 'jason.chan@instructor.com'],
            ['Jason Hafner', 'jason.hafner@instructor.com'],
            ['Javier Yanez', 'javier.yanez@instructor.com'],
            ['Jay Mendelson', 'jay.mendelson@instructor.com'],
            ['Jean-Luc Falcone', 'jean.luc.falcone@instructor.com'],
            ['Jeanne M. Liedtka', 'jeanne.m.liedtka@instructor.com'],
            ['Jeff Bisti', 'jeff.bisti@instructor.com'],
            ['Jeff Crume', 'jeff.crume@instructor.com'],
            ['Jeff Flesher', 'jeff.flesher@instructor.com'],
            ['Jeff Grossman', 'jeff.grossman@instructor.com'],
            ['Jeff Leek, PhD', 'jeff.leek.phd@instructor.com'],
            ['Jeffery Atik', 'jeffery.atik@instructor.com'],
            ['Jeffrey Loewenstein', 'jeffrey.loewenstein@instructor.com'],
            ['Jeffrey R. Chasnov', 'jeffrey.r.chasnov@instructor.com'],
            ['Jeffrey Sachs', 'jeffrey.sachs@instructor.com'],
            ['Jeffrey Slahor', 'jeffrey.slahor@instructor.com'],
            ['Jelani Zarif', 'jelani.zarif@instructor.com'],
            ['Jem Corcoran', 'jem.corcoran@instructor.com'],
            ['Jennifer Campbell', 'jennifer.campbell@instructor.com'],
            ['Jennifer Golbeck', 'jennifer.golbeck@instructor.com'],
            ['Jennifer Vogel, Online Programs Coordinator', 'jennifer.vogel.online.programs.coordinator@instructor.com'],
            ['Jennifer Zabel', 'jennifer.zabel@instructor.com'],
            ['Jerry Cooperstein', 'jerry.cooperstein@instructor.com'],
            ['Jesper Tegner', 'jesper.tegner@instructor.com'],
            ['Jessica M. Roosth', 'jessica.m.roosth@instructor.com'],
            ['Jessica Shurson', 'jessica.shurson@instructor.com'],
            ['Jessica Wachter', 'jessica.wachter@instructor.com'],
            ['Jianbo Shi', 'jianbo.shi@instructor.com'],
            ['Jiang Shuo', 'jiang.shuo@instructor.com'],
            ['Jim Fong', 'jim.fong@instructor.com'],
            ['Jim Sullivan', 'jim.sullivan@instructor.com'],
            ['Jimeng Sun', 'jimeng.sun@instructor.com'],
            ['Jinseok Kim', 'jinseok.kim@instructor.com'],
            ['Jizhou Kang', 'jizhou.kang@instructor.com'],
            ['Joe A. Bradley', 'joe.a.bradley@instructor.com'],
            ['Joe Warren', 'joe.warren@instructor.com'],
            ['Joel Coffman', 'joel.coffman@instructor.com'],
            ['Johan David Michels', 'johan.david.michels@instructor.com'],
            ['John C. Hart', 'john.c.hart@instructor.com'],
            ['John Doerr', 'john.doerr@instructor.com'],
            ['John Greiner', 'john.greiner@instructor.com'],
            ['John Kim', 'john.kim@instructor.com'],
            ['John McGready, PhD, MS', 'john.mcgready.phd.ms@instructor.com'],
            ['John Mulvey - Princeton University', 'john.mulvey.princeton.university@instructor.com'],
            ['John Richards', 'john.richards@instructor.com'],
            ['John Robertson', 'john.robertson@instructor.com'],
            ['John Rofrano', 'john.rofrano@instructor.com'],
            ['John Sparks', 'john.sparks@instructor.com'],
            ['John W. Daily', 'john.w.daily@instructor.com'],
            ['John Wagnon', 'john.wagnon@instructor.com'],
            ['Jon Reifschneider', 'jon.reifschneider@instructor.com'],
            ['Jonah Berger', 'jonah.berger@instructor.com'],
            ['Jonas Latt', 'jonas.latt@instructor.com'],
            ['Jonathan Agger, MRSC', 'jonathan.agger.mrsc@instructor.com'],
            ['Jonathan Kelly', 'jonathan.kelly@instructor.com'],
            ['Jong-Moon Chung', 'jong.moon.chung@instructor.com'],
            ['Joonwoo Bae', 'joonwoo.bae@instructor.com'],
            ['Jordan Bakerman', 'jordan.bakerman@instructor.com'],
            ['Jordan Wilson', 'jordan.wilson@instructor.com'],
            ['Joseph A Konstan', 'joseph.a.konstan@instructor.com'],
            ['Joseph Casola', 'joseph.casola@instructor.com'],
            ['Joseph D. Ma', 'joseph.d.ma@instructor.com'],
            ['Joseph Santarcangelo', 'joseph.santarcangelo@instructor.com'],
            ['Joseph T. Wu (HKU)', 'joseph.t.wu.hku@instructor.com'],
            ['Joseph T. Yun', 'joseph.t.yun@instructor.com'],
            ['Joseph W. Cutrone, PhD', 'joseph.w.cutrone.phd@instructor.com'],
            ['Jousef Murad', 'jousef.murad@instructor.com'],
            ['Juan H Klopper', 'juan.h.klopper@instructor.com'],
            ['Judy Richardson', 'judy.richardson@instructor.com'],
            ['Juha Plosila', 'juha.plosila@instructor.com'],
            ['Jukka Pekka Matinlinna', 'jukka.pekka.matinlinna@instructor.com'],
            ['Julian Brooks', 'julian.brooks@instructor.com'],
            ['Julian Nowag', 'julian.nowag@instructor.com'],
            ['Julie Elkins', 'julie.elkins@instructor.com'],
            ['Julie Pai', 'julie.pai@instructor.com'],
            ['Juliet Gopinath', 'juliet.gopinath@instructor.com'],
            ['Juliet Jane Fall', 'juliet.jane.fall@instructor.com'],
            ['June Gruber', 'june.gruber@instructor.com'],
            ['Justin Cannady', 'justin.cannady@instructor.com'],
            ['Kamryn Vinson', 'kamryn.vinson@instructor.com'],
            ['Kang, Youn-Bae', 'kang.youn.bae@instructor.com'],
            ['Karen A. Monsen, PhD, RN, FAMIA, FNAP, FAAN', 'karen.a.monsen.phd.rn.famia.fnap.faan@instructor.com'],
            ['Karen Reivich, Ph.D.', 'karen.reivich.ph.d@instructor.com'],
            ['Karl Schmedders', 'karl.schmedders@instructor.com'],
            ['Kashmira Shukla', 'kashmira.shukla@instructor.com'],
            ['Kasie Kyle', 'kasie.kyle@instructor.com'],
            ['Kasper Daniel Hansen, PhD', 'kasper.daniel.hansen.phd@instructor.com'],
            ['Kate Sullivan', 'kate.sullivan@instructor.com'],
            ['Kathleen Alsup', 'kathleen.alsup@instructor.com'],
            ['Kathy Soder', 'kathy.soder@instructor.com'],
            ['Katie Duitsman', 'katie.duitsman@instructor.com'],
            ['Katrina Glaeser Poole', 'katrina.glaeser.poole@instructor.com'],
            ['Kay Malcolm', 'kay.malcolm@instructor.com'],
            ['Keanan Duffty', 'keanan.duffty@instructor.com'],
            ['Keatron Evans', 'keatron.evans@instructor.com'],
            ['Keith Gibson', 'keith.gibson@instructor.com'],
            ['Kelley Conrad', 'kelley.conrad@instructor.com'],
            ['Kelli Sullivan', 'kelli.sullivan@instructor.com'],
            ['Ken English', 'ken.english@instructor.com'],
            ['Ken Reily', 'ken.reily@instructor.com'],
            ['Keng Hsu', 'keng.hsu@instructor.com'],
            ['Kennedy Behrman', 'kennedy.behrman@instructor.com'],
            ['Kenneth J. Pienta, M.D.', 'kenneth.j.pienta.m.d@instructor.com'],
            ['Kenneth Rogerson', 'kenneth.rogerson@instructor.com'],
            ['Kenneth Valkenburg', 'kenneth.valkenburg@instructor.com'],
            ['Kenneth W T Leung', 'kenneth.w.t.leung@instructor.com'],
            ['Kenny Mobley', 'kenny.mobley@instructor.com'],
            ['Kenny Wong', 'kenny.wong@instructor.com'],
            ['Kentaro Toyama', 'kentaro.toyama@instructor.com'],
            ['Keon Jae Lee', 'keon.jae.lee@instructor.com'],
            ['Kerby Shedden', 'kerby.shedden@instructor.com'],
            ['Keri Althoff, PhD, MPH', 'keri.althoff.phd.mph@instructor.com'],
            ['Kerstin Alfes', 'kerstin.alfes@instructor.com'],
            ['Kes McCormick', 'kes.mccormick@instructor.com'],
            ['Kevin  Cardwell', 'kevin.cardwell@instructor.com'],
            ['Kevin Coyle', 'kevin.coyle@instructor.com'],
            ['Kevin E. Bonine, PhD', 'kevin.e.bonine.phd@instructor.com'],
            ['Kevin Hartman', 'kevin.hartman@instructor.com'],
            ['Kevin Leyton-Brown', 'kevin.leyton.brown@instructor.com'],
            ['Kevin Liang', 'kevin.liang@instructor.com'],
            ['Kevin Lynch', 'kevin.lynch@instructor.com'],
            ['Kevin McFaul', 'kevin.mcfaul@instructor.com'],
            ['Kevin Noelsaint', 'kevin.noelsaint@instructor.com'],
            ['Kevin Vaccaro', 'kevin.vaccaro@instructor.com'],
            ['Kevin Wayne', 'kevin.wayne@instructor.com'],
            ['Kevin Wendt', 'kevin.wendt@instructor.com'],
            ['Kevin Werbach', 'kevin.werbach@instructor.com'],
            ['Kevin Williams', 'kevin.williams@instructor.com'],
            ['Kevyn Collins-Thompson', 'kevyn.collins.thompson@instructor.com'],
            ['Khristian Serrano', 'khristian.serrano@instructor.com'],
            ['Kiah Ong', 'kiah.ong@instructor.com'],
            ['Kian Katanforoosh', 'kian.katanforoosh@instructor.com'],
            ['Kiana McDaniel', 'kiana.mcdaniel@instructor.com'],
            ['Kil Hyun Kwon', 'kil.hyun.kwon@instructor.com'],
            ['Killian Lynch', 'killian.lynch@instructor.com'],
            ['Kim, Nack Joon', 'kim.nack.joon@instructor.com'],
            ['Kim, Sung-Joon', 'kim.sung.joon@instructor.com'],
            ['Kimberly B. McLain, Ph.D.', 'kimberly.b.mclain.ph.d@instructor.com'],
            ['Kirby Kohlmorgen', 'kirby.kohlmorgen@instructor.com'],
            ['Klaus Drechsler', 'klaus.drechsler@instructor.com'],
            ['Klaus Heine', 'klaus.heine@instructor.com'],
            ['Kolan M. Reddy', 'kolan.m.reddy@instructor.com'],
            ['Konstantinos Stylianou', 'konstantinos.stylianou@instructor.com'],
            ['Kopal Garg', 'kopal.garg@instructor.com'],
            ['Kostas Daniilidis', 'kostas.daniilidis@instructor.com'],
            ['Kristen Walcott-Justice', 'kristen.walcott.justice@instructor.com'],
            ['Ksenia Anisimova', 'ksenia.anisimova@instructor.com'],
            ['Kwang-Soon Kim', 'kwang.soon.kim@instructor.com'],
            ['Kwok-Yung Yuen (HKU)', 'kwok.yung.yuen.hku@instructor.com'],
            ['Kwon, Kil Hyun', 'kwon.kil.hyun@instructor.com'],
            ['Kyle Bradbury', 'kyle.bradbury@instructor.com'],
            ['Lama Sleem', 'lama.sleem@instructor.com'],
            ['Lambros Katafygiotis', 'lambros.katafygiotis@instructor.com'],
            ['Lana Yarosh', 'lana.yarosh@instructor.com'],
            ['Larry Randles Lagerstrom', 'larry.randles.lagerstrom@instructor.com'],
            ['Lauge Peter Westergaard Clausen', 'lauge.peter.westergaard.clausen@instructor.com'],
            ['Laura K. Wiley, PhD', 'laura.k.wiley.phd@instructor.com'],
            ['Laura S. Kabiri', 'laura.s.kabiri@instructor.com'],
            ['Laurence Baker', 'laurence.baker@instructor.com'],
            ['Laurence Moroney', 'laurence.moroney@instructor.com'],
            ['Laurie Cozart', 'laurie.cozart@instructor.com'],
            ['Lavanya Thiruvali Sunderarajan', 'lavanya.thiruvali.sunderarajan@instructor.com'],
            ['Lawrence Carin', 'lawrence.carin@instructor.com'],
            ['Lawrence Osborn', 'lawrence.osborn@instructor.com'],
            ['Leire Ahedo', 'leire.ahedo@instructor.com'],
            ['Lena Wahlberg', 'lena.wahlberg@instructor.com'],
            ['Leo Porter', 'leo.porter@instructor.com'],
            ['Leonard E. White, Ph.D.', 'leonard.e.white.ph.d@instructor.com'],
            ['Leslie Reynolds', 'leslie.reynolds@instructor.com'],
            ['Lija Hogan', 'lija.hogan@instructor.com'],
            ['Liliana Florea, PhD', 'liliana.florea.phd@instructor.com'],
            ['Lincoln Pratson', 'lincoln.pratson@instructor.com'],
            ['Linden Lu', 'linden.lu@instructor.com'],
            ['Lindred Greer', 'lindred.greer@instructor.com'],
            ['Lisa A. Holden', 'lisa.a.holden@instructor.com'],
            ['Lisa Montanaro', 'lisa.montanaro@instructor.com'],
            ['Lisa Shufro', 'lisa.shufro@instructor.com'],
            ['Liu Jing', 'liu.jing@instructor.com'],
            ['Liz Durango-Cohen', 'liz.durango.cohen@instructor.com'],
            ['Loren Terveen', 'loren.terveen@instructor.com'],
            ['Lori Lane', 'lori.lane@instructor.com'],
            ['Louis A. Bloomfield', 'louis.a.bloomfield@instructor.com'],
            ['Luann J. Lynch', 'luann.j.lynch@instructor.com'],
            ['Luay Nakhleh', 'luay.nakhleh@instructor.com'],
            ['Luis Serrano', 'luis.serrano@instructor.com'],
            ['M.S. Krishnan', 'm.s.krishnan@instructor.com'],
            ['MOUSSA DOUMBIA', 'moussa.doumbia@instructor.com'],
            ['Madhura Lohokare', 'madhura.lohokare@instructor.com'],
            ['Magdalena Bouza', 'magdalena.bouza@instructor.com'],
            ['Maighdlin Anderson', 'maighdlin.anderson@instructor.com'],
            ['Majed Al-Ghandour', 'majed.al.ghandour@instructor.com'],
            ['Malik Peiris (HKU)', 'malik.peiris.hku@instructor.com'],
            ['Manuel Roveri', 'manuel.roveri@instructor.com'],
            ['Manuela Antonelli', 'manuela.antonelli@instructor.com'],
            ['Marc Brackett', 'marc.brackett@instructor.com'],
            ['Marc Huber', 'marc.huber@instructor.com'],
            ['Marc Lipsitch (Harvard)', 'marc.lipsitch.harvard@instructor.com'],
            ['Marc Peter Deisenroth', 'marc.peter.deisenroth@instructor.com'],
            ['Marc Quibell', 'marc.quibell@instructor.com'],
            ['Marc Thompson', 'marc.thompson@instructor.com'],
            ['Marc van Oostendorp', 'marc.van.oostendorp@instructor.com'],
            ['Marcello Restelli', 'marcello.restelli@instructor.com'],
            ['Marcelo Gleiser', 'marcelo.gleiser@instructor.com'],
            ['Marco Anisetti', 'marco.anisetti@instructor.com'],
            ['Marco Brambilla', 'marco.brambilla@instructor.com'],
            ['Marcus J. C. Long', 'marcus.j.c.long@instructor.com'],
            ['Marek Czernek', 'marek.czernek@instructor.com'],
            ['Margaret Wooldridge, Ph.D.', 'margaret.wooldridge.ph.d@instructor.com'],
            ['Maria Colgan', 'maria.colgan@instructor.com'],
            ['Maria Gavilan-Alfonso', 'maria.gavilan.alfonso@instructor.com'],
            ['Maria Huachen Zhu (HKU)', 'maria.huachen.zhu.hku@instructor.com'],
            ['Mario Ferraro', 'mario.ferraro@instructor.com'],
            ['Marion Festing', 'marion.festing@instructor.com'],
            ['Mariya Eranova', 'mariya.eranova@instructor.com'],
            ['Marjaneh Issapour', 'marjaneh.issapour@instructor.com'],
            ['Mark  Bocko', 'mark.bocko@instructor.com'],
            ['Mark Bremer', 'mark.bremer@instructor.com'],
            ['Mark Bylok', 'mark.bylok@instructor.com'],
            ['Mark C. Serreze', 'mark.c.serreze@instructor.com'],
            ['Mark Haefele', 'mark.haefele@instructor.com'],
            ['Mark Hornick', 'mark.hornick@instructor.com'],
            ['Mark J Grover', 'mark.j.grover@instructor.com'],
            ['Mark Jit (LSHTM)', 'mark.jit.lshtm@instructor.com'],
            ['Mark New', 'mark.new@instructor.com'],
            ['Mark Newman', 'mark.newman@instructor.com'],
            ['Mark Price', 'mark.price@instructor.com'],
            ['Mark Roepke', 'mark.roepke@instructor.com'],
            ['Mark Veljkov', 'mark.veljkov@instructor.com'],
            ['Markus Mueller', 'markus.mueller@instructor.com'],
            ['Markus Stoffel', 'markus.stoffel@instructor.com'],
            ['Marla Noel', 'marla.noel@instructor.com'],
            ['Martha White', 'martha.white@instructor.com'],
            ['Martin Beniston', 'martin.beniston@instructor.com'],
            ['Martin Casstevens', 'martin.casstevens@instructor.com'],
            ['Martin Dubois', 'martin.dubois@instructor.com'],
            ['Martin Gollogly', 'martin.gollogly@instructor.com'],
            ['Martin Keen', 'martin.keen@instructor.com'],
            ['Martin Kohn', 'martin.kohn@instructor.com'],
            ['Martin Pohl', 'martin.pohl@instructor.com'],
            ['Martin Schlaepfer', 'martin.schlaepfer@instructor.com'],
            ['Martin Timmerman', 'martin.timmerman@instructor.com'],
            ['Martine Haas', 'martine.haas@instructor.com'],
            ['Marty Wrin', 'marty.wrin@instructor.com'],
            ['Mary Ellen Foster', 'mary.ellen.foster@instructor.com'],
            ['Mary Gentile', 'mary.gentile@instructor.com'],
            ['Mary-Hunter McDonnell', 'mary.hunter.mcdonnell@instructor.com'],
            ['Matan Shelomi', 'matan.shelomi@instructor.com'],
            ['MathWorks Instructors', 'mathworks.instructors@instructor.com'],
            ['Matija Matisic', 'matija.matisic@instructor.com'],
            ['Mats Lindroos', 'mats.lindroos@instructor.com'],
            ['Matt Harrison', 'matt.harrison@instructor.com'],
            ['Matt Kurtz', 'matt.kurtz@instructor.com'],
            ['Matt Rich', 'matt.rich@instructor.com'],
            ['Matt Rushton', 'matt.rushton@instructor.com'],
            ['Matteo Vincenzo Rocco', 'matteo.vincenzo.rocco@instructor.com'],
            ['Matthew Bidwell', 'matthew.bidwell@instructor.com'],
            ['Matthew Caesar', 'matthew.caesar@instructor.com'],
            ['Matthew Heiner', 'matthew.heiner@instructor.com'],
            ['Matthew Hutchens', 'matthew.hutchens@instructor.com'],
            ['Matthew Lungren', 'matthew.lungren@instructor.com'],
            ['Matthew O. Jackson', 'matthew.o.jackson@instructor.com'],
            ['Matthew Wright', 'matthew.wright@instructor.com'],
            ['Matthijs Rooduijn', 'matthijs.rooduijn@instructor.com'],
            ['Maurice Schweitzer', 'maurice.schweitzer@instructor.com'],
            ['Mauro Mocerino', 'mauro.mocerino@instructor.com'],
            ['Max Babayev', 'max.babayev@instructor.com'],
            ['Max Kraev', 'max.kraev@instructor.com'],
            ['Max Pumperla', 'max.pumperla@instructor.com'],
            ['Maya Adam, MD', 'maya.adam.md@instructor.com'],
            ['Megan Smith Branch', 'megan.smith.branch@instructor.com'],
            ['Megan Thompson', 'megan.thompson@instructor.com'],
            ['Melissa Barandiaran', 'melissa.barandiaran@instructor.com'],
            ['Melissa Clarke', 'melissa.clarke@instructor.com'],
            ['Melissa Wood', 'melissa.wood@instructor.com'],
            ['Melvin Smith', 'melvin.smith@instructor.com'],
            ['Menna ElSharkawy', 'menna.elsharkawy@instructor.com'],
            ['Mia Minnes', 'mia.minnes@instructor.com'],
            ['Michael Beach', 'michael.beach@instructor.com'],
            ['Michael D. Ekstrand', 'michael.d.ekstrand@instructor.com'],
            ['Michael G. Kahn, MD, PhD', 'michael.g.kahn.md.phd@instructor.com'],
            ['Michael Genesereth', 'michael.genesereth@instructor.com'],
            ['Michael J. Readey, Ph.D.', 'michael.j.readey.ph.d@instructor.com'],
            ['Michael Levin', 'michael.levin@instructor.com'],
            ['Michael Mannino', 'michael.mannino@instructor.com'],
            ['Michael Nebeling', 'michael.nebeling@instructor.com'],
            ['Michael R. Pratt', 'michael.r.pratt@instructor.com'],
            ['Michael Reardon', 'michael.reardon@instructor.com'],
            ['Michael S. Gutter, Ph.D.', 'michael.s.gutter.ph.d@instructor.com'],
            ['Michael Shields', 'michael.shields@instructor.com'],
            ['Michael W. Anderson, FRSC', 'michael.w.anderson.frsc@instructor.com'],
            ['Michael Walker', 'michael.walker@instructor.com'],
            ['Michael Weisberg', 'michael.weisberg@instructor.com'],
            ['Michael Whitman, Ph.D., CISM, CISSP', 'michael.whitman.ph.d.cism.cissp@instructor.com'],
            ['Michael Worthington', 'michael.worthington@instructor.com'],
            ['Michaela Zint', 'michaela.zint@instructor.com'],
            ['Michel van der Wel', 'michel.van.der.wel@instructor.com'],
            ['Michele Ensor', 'michele.ensor@instructor.com'],
            ['Michelle Malcher', 'michelle.malcher@instructor.com'],
            ['Michelle Saltoun', 'michelle.saltoun@instructor.com'],
            ['Microsoft', 'microsoft@instructor.com'],
            ['Miguel Alcobia', 'miguel.alcobia@instructor.com'],
            ['Miguel Maldonado', 'miguel.maldonado@instructor.com'],
            ['Mihaela Pertea, PhD', 'mihaela.pertea.phd@instructor.com'],
            ['Mike', 'mike@instructor.com'],
            ['Mike Barinek', 'mike.barinek@instructor.com'],
            ['Mike Brown', 'mike.brown@instructor.com'],
            ['Mike Chambers', 'mike.chambers@instructor.com'],
            ['Mike Fitzpatrick', 'mike.fitzpatrick@instructor.com'],
            ['Mike Hervey', 'mike.hervey@instructor.com'],
            ['Mike Ryan', 'mike.ryan@instructor.com'],
            ['Mike Yao', 'mike.yao@instructor.com'],
            ['Mildred Cho', 'mildred.cho@instructor.com'],
            ['Mohamed Touiti', 'mohamed.touiti@instructor.com'],
            ['Mohammed Al M.', 'mohammed.al.m@instructor.com'],
            ['Mohit Chandarana', 'mohit.chandarana@instructor.com'],
            ['MongoDB University', 'mongodb.university@instructor.com'],
            ['MongoDB for Academia', 'mongodb.for.academia@instructor.com'],
            ['Morgan Willis', 'morgan.willis@instructor.com'],
            ['Mr Sebastian Fricke', 'mr.sebastian.fricke@instructor.com'],
            ['Ms Sarah Sherman', 'ms.sarah.sherman@instructor.com'],
            ['Muhammad Saad uddin', 'muhammad.saad.uddin@instructor.com'],
            ['Muhammad Yahya', 'muhammad.yahya@instructor.com'],
            ['Muriel Figueredo Franco', 'muriel.figueredo.franco@instructor.com'],
            ['Murtaza Haider', 'murtaza.haider@instructor.com'],
            ['Myrthe van Dieijen', 'myrthe.van.dieijen@instructor.com'],
            ['NASM Faculty', 'nasm.faculty@instructor.com'],
            ['NVIDIA Training', 'nvidia.training@instructor.com'],
            ['Nakul H. Navarange', 'nakul.h.navarange@instructor.com'],
            ['Nancy Wang', 'nancy.wang@instructor.com'],
            ['Natasa Brouwer', 'natasa.brouwer@instructor.com'],
            ['Natasha Balac, Ph.D.', 'natasha.balac.ph.d@instructor.com'],
            ['Natasha Sarin', 'natasha.sarin@instructor.com'],
            ['Nathan Leniz', 'nathan.leniz@instructor.com'],
            ['Nathaniel Green', 'nathaniel.green@instructor.com'],
            ['Neal Abrams', 'neal.abrams@instructor.com'],
            ['Neelesh Tiruviluamala', 'neelesh.tiruviluamala@instructor.com'],
            ['Neil Rhodes', 'neil.rhodes@instructor.com'],
            ['Neil Thawani', 'neil.thawani@instructor.com'],
            ['Nguyen Gia Tuan', 'nguyen.gia.tuan@instructor.com'],
            ['Nicholas Carnes', 'nicholas.carnes@instructor.com'],
            ['Nicholas James Provart', 'nicholas.james.provart@instructor.com'],
            ['Nicholas Saba', 'nicholas.saba@instructor.com'],
            ['Nick Eubank', 'nick.eubank@instructor.com'],
            ['Nick Santos', 'nick.santos@instructor.com'],
            ['Nick Tompkins', 'nick.tompkins@instructor.com'],
            ['Nicky Bull', 'nicky.bull@instructor.com'],
            ['Nicola Gatti', 'nicola.gatti@instructor.com'],
            ['Nicola Osborne', 'nicola.osborne@instructor.com'],
            ['Nicolas Glady', 'nicolas.glady@instructor.com'],
            ['Nicole Alvelo', 'nicole.alvelo@instructor.com'],
            ['Nicole Ball', 'nicole.ball@instructor.com'],
            ['Nigam Shah', 'nigam.shah@instructor.com'],
            ['Niketan Pansare', 'niketan.pansare@instructor.com'],
            ['Niklas Selberg', 'niklas.selberg@instructor.com'],
            ['Nikola Trica', 'nikola.trica@instructor.com'],
            ['Nikolaus Correll', 'nikolaus.correll@instructor.com'],
            ['Nikolay Manchev', 'nikolay.manchev@instructor.com'],
            ['Nikolay Vyahhi', 'nikolay.vyahhi@instructor.com'],
            ['Nikos Mattheos', 'nikos.mattheos@instructor.com'],
            ['Noah Gans', 'noah.gans@instructor.com'],
            ['Noah Gift', 'noah.gift@instructor.com'],
            ['Noam  Nisan', 'noam.nisan@instructor.com'],
            ['Noel J. Bergman', 'noel.j.bergman@instructor.com'],
            ['Oksana Hoeckele', 'oksana.hoeckele@instructor.com'],
            ['Oliver Belin', 'oliver.belin@instructor.com'],
            ['Omnya Khaled', 'omnya.khaled@instructor.com'],
            ['Omodiaogbe Samuel', 'omodiaogbe.samuel@instructor.com'],
            ['Onlea support', 'onlea.support@instructor.com'],
            ['Oren Perez', 'oren.perez@instructor.com'],
            ['Orestis Malaspinas', 'orestis.malaspinas@instructor.com'],
            ['Orlando Gentil', 'orlando.gentil@instructor.com'],
            ['Owen Astrachan', 'owen.astrachan@instructor.com'],
            ['P. Brighten Godfrey', 'p.brighten.godfrey@instructor.com'],
            ['Pankaj Setia', 'pankaj.setia@instructor.com'],
            ['Paolo Matthiae', 'paolo.matthiae@instructor.com'],
            ['Parham Aarabi', 'parham.aarabi@instructor.com'],
            ['Patricia Werhane', 'patricia.werhane@instructor.com'],
            ['Patrick Ester', 'patrick.ester@instructor.com'],
            ['Patrick J O\'Malley, D.Sc', 'patrick.j.o.malley.d.sc@instructor.com'],
            ['Patrick Wheeler', 'patrick.wheeler@instructor.com'],
            ['Paul Behrens', 'paul.behrens@instructor.com'],
            ['Paul Bendich', 'paul.bendich@instructor.com'],
            ['Paul Bloom', 'paul.bloom@instructor.com'],
            ['Paul Cerrato', 'paul.cerrato@instructor.com'],
            ['Paul Christensen', 'paul.christensen@instructor.com'],
            ['Paul Doherty, PhD', 'paul.doherty.phd@instructor.com'],
            ['Paul Gries', 'paul.gries@instructor.com'],
            ['Paul Harris, PhD', 'paul.harris.phd@instructor.com'],
            ['Paul Jan', 'paul.jan@instructor.com'],
            ['Paul Komor', 'paul.komor@instructor.com'],
            ['Paul Lu', 'paul.lu@instructor.com'],
            ['Paul Myers, Ph.D', 'paul.myers.ph.d@instructor.com'],
            ['Paul Nagy, PhD, FSIIM', 'paul.nagy.phd.fsiim@instructor.com'],
            ['Paul Rea', 'paul.rea@instructor.com'],
            ['Paul Resnick', 'paul.resnick@instructor.com'],
            ['Paula Caproni', 'paula.caproni@instructor.com'],
            ['Pavel  Pevzner', 'pavel.pevzner@instructor.com'],
            ['Pedro Alvarez', 'pedro.alvarez@instructor.com'],
            ['Peggy Mason', 'peggy.mason@instructor.com'],
            ['Per Harald Borgen', 'per.harald.borgen@instructor.com'],
            ['Perry G Mehrling', 'perry.g.mehrling@instructor.com'],
            ['Pete Higgins', 'pete.higgins@instructor.com'],
            ['Peter A.G. van Bergeijk', 'peter.a.g.van.bergeijk@instructor.com'],
            ['Peter Fader', 'peter.fader@instructor.com'],
            ['Peter O\'Connor', 'peter.o.connor@instructor.com'],
            ['Peter Rielly', 'peter.rielly@instructor.com'],
            ['Peter Small', 'peter.small@instructor.com'],
            ['Peter Styliadis', 'peter.styliadis@instructor.com'],
            ['Petros Tsantoulis', 'petros.tsantoulis@instructor.com'],
            ['Philip Bennett', 'philip.bennett@instructor.com'],
            ['Philip Hans Franses', 'philip.hans.franses@instructor.com'],
            ['Philip John Currie, PhD', 'philip.john.currie.phd@instructor.com'],
            ['Philip Matuszak', 'philip.matuszak@instructor.com'],
            ['Philip S. Boonstra', 'philip.s.boonstra@instructor.com'],
            ['Phillip Compeau', 'phillip.compeau@instructor.com'],
            ['Pinar Akman', 'pinar.akman@instructor.com'],
            ['Polong Lin', 'polong.lin@instructor.com'],
            ['Pranav Rajpurkar', 'pranav.rajpurkar@instructor.com'],
            ['Prasanjit Singh', 'prasanjit.singh@instructor.com'],
            ['Prasanth Kumar Palani', 'prasanth.kumar.palani@instructor.com'],
            ['Praveen Mittal', 'praveen.mittal@instructor.com'],
            ['Predrag Klasnja', 'predrag.klasnja@instructor.com'],
            ['Priya Jha', 'priya.jha@instructor.com'],
            ['Priya Kapoor', 'priya.kapoor@instructor.com'],
            ['Priyank Chodisetti', 'priyank.chodisetti@instructor.com'],
            ['Prof Marco Gillies', 'prof.marco.gillies@instructor.com'],
            ['Prof Robert Akid', 'prof.robert.akid@instructor.com'],
            ['Prof Stuart Lyon', 'prof.stuart.lyon@instructor.com'],
            ['Prof.  Lena Neij', 'prof.lena.neij@instructor.com'],
            ['Prof. Christine Wamsler', 'prof.christine.wamsler@instructor.com'],
            ['Prof. Dorian A. Canelas', 'prof.dorian.a.canelas@instructor.com'],
            ['Prof. Harriet Bulkeley', 'prof.harriet.bulkeley@instructor.com'],
            ['Prof. Hossam Haick', 'prof.hossam.haick@instructor.com'],
            ['Prof. James Evans', 'prof.james.evans@instructor.com'],
            ['Prof. Joe Wolfe', 'prof.joe.wolfe@instructor.com'],
            ['Prof. Kelleann Foster', 'prof.kelleann.foster@instructor.com'],
            ['Prof. Nicholas Turner', 'prof.nicholas.turner@instructor.com'],
            ['Prof. Nigel Scrutton', 'prof.nigel.scrutton@instructor.com'],
            ['Prof. Vic Murray, PhD', 'prof.vic.murray.phd@instructor.com'],
            ['Prof. Yvonne Cafik Harrison, PhD', 'prof.yvonne.cafik.harrison.phd@instructor.com'],
            ['Professor Andy Clark', 'professor.andy.clark@instructor.com'],
            ['Professor Barbara Webb', 'professor.barbara.webb@instructor.com'],
            ['Professor Daniel Chamovitz, Ph.D.', 'professor.daniel.chamovitz.ph.d@instructor.com'],
            ['Professor Duncan Pritchard', 'professor.duncan.pritchard@instructor.com'],
            ['Professor John MacBeath', 'professor.john.macbeath@instructor.com'],
            ['Professor John Peacock', 'professor.john.peacock@instructor.com'],
            ['Professor Keith M. Martin', 'professor.keith.m.martin@instructor.com'],
            ['Professor Mark Harris', 'professor.mark.harris@instructor.com'],
            ['Professor Michela Massimi', 'professor.michela.massimi@instructor.com'],
            ['Professor Pascal Van Hentenryck', 'professor.pascal.van.hentenryck@instructor.com'],
            ['Professor Peter Komisarczuk', 'professor.peter.komisarczuk@instructor.com'],
            ['Professor Yvonne Breyer', 'professor.yvonne.breyer@instructor.com'],
            ['Qasim Ijaz', 'qasim.ijaz@instructor.com'],
            ['Qiang Guo', 'qiang.guo@instructor.com'],
            ['Qin (Christine) Lv', 'qin.christine.lv@instructor.com'],
            ['R. Edward Freeman', 'r.edward.freeman@instructor.com'],
            ['R. Polk Wagner', 'r.polk.wagner@instructor.com'],
            ['RICCARDO REBONATO - EDHEC BUSINESS SCHOOL', 'riccardo.rebonato.edhec.business.school@instructor.com'],
            ['Racquel Stephens', 'racquel.stephens@instructor.com'],
            ['Rafael Lopes', 'rafael.lopes@instructor.com'],
            ['Rafiq Wayani', 'rafiq.wayani@instructor.com'],
            ['Raghu Iyengar', 'raghu.iyengar@instructor.com'],
            ['Rahul Nandkishore', 'rahul.nandkishore@instructor.com'],
            ['Rahul Rai', 'rahul.rai@instructor.com'],
            ['Rahul Rajaput', 'rahul.rajaput@instructor.com'],
            ['Raj Echambadi', 'raj.echambadi@instructor.com'],
            ['Rajesh P. N. Rao', 'rajesh.p.n.rao@instructor.com'],
            ['Rajvir Dua', 'rajvir.dua@instructor.com'],
            ['Ralph Lydic, Ph.D.', 'ralph.lydic.ph.d@instructor.com'],
            ['Ramanujam Srinivasan', 'ramanujam.srinivasan@instructor.com'],
            ['Ramesh Sannareddy', 'ramesh.sannareddy@instructor.com'],
            ['Randal C. Picker', 'randal.c.picker@instructor.com'],
            ['Randy Hlavac', 'randy.hlavac@instructor.com'],
            ['Raquel Prado', 'raquel.prado@instructor.com'],
            ['Rasmus Nielsen', 'rasmus.nielsen@instructor.com'],
            ['Rav Ahuja', 'rav.ahuja@instructor.com'],
            ['Ravi Iyengar, PhD', 'ravi.iyengar.phd@instructor.com'],
            ['Ravi Mehta', 'ravi.mehta@instructor.com'],
            ['Ray Lopez, Ph.D.', 'ray.lopez.ph.d@instructor.com'],
            ['Rebecca Bleibaum', 'rebecca.bleibaum@instructor.com'],
            ['Rebecca Stein', 'rebecca.stein@instructor.com'],
            ['Rebekah May', 'rebekah.may@instructor.com'],
            ['Red Hat Training', 'red.hat.training@instructor.com'],
            ['Remi Badonnel', 'remi.badonnel@instructor.com'],
            ['Reza Farivar', 'reza.farivar@instructor.com'],
            ['Ricardo Sanfelice', 'ricardo.sanfelice@instructor.com'],
            ['Richa Arora', 'richa.arora@instructor.com'],
            ['Richard Boyatzis', 'richard.boyatzis@instructor.com'],
            ['Richard Neitzel', 'richard.neitzel@instructor.com'],
            ['Richard Paap', 'richard.paap@instructor.com'],
            ['Richard Ryan', 'richard.ryan@instructor.com'],
            ['Richard Shell', 'richard.shell@instructor.com'],
            ['Richard Stempniak', 'richard.stempniak@instructor.com'],
            ['Richard Waterman', 'richard.waterman@instructor.com'],
            ['Richard White', 'richard.white@instructor.com'],
            ['Rick Smith', 'rick.smith@instructor.com'],
            ['Rita Kukafka', 'rita.kukafka@instructor.com'],
            ['Ro Kinzler, Ph.D.', 'ro.kinzler.ph.d@instructor.com'],
            ['Rob A. Rutenbar', 'rob.a.rutenbar@instructor.com'],
            ['Rob Knight', 'rob.knight@instructor.com'],
            ['Robbie Loewith', 'robbie.loewith@instructor.com'],
            ['Robert  Clark', 'robert.clark@instructor.com'],
            ['Robert Crowe', 'robert.crowe@instructor.com'],
            ['Robert Dittmar', 'robert.dittmar@instructor.com'],
            ['Robert Duvall', 'robert.duvall@instructor.com'],
            ['Robert Ghrist', 'robert.ghrist@instructor.com'],
            ['Robert Heinsch', 'robert.heinsch@instructor.com'],
            ['Robert Lehman', 'robert.lehman@instructor.com'],
            ['Robert Mazzeo, Ph.D.', 'robert.mazzeo.ph.d@instructor.com'],
            ['Robert McLeod', 'robert.mcleod@instructor.com'],
            ['Robert Monarch', 'robert.monarch@instructor.com'],
            ['Robert Sedgewick', 'robert.sedgewick@instructor.com'],
            ['Robert Shiller', 'robert.shiller@instructor.com'],
            ['Robert Van Saun', 'robert.van.saun@instructor.com'],
            ['Robert Wilken', 'robert.wilken@instructor.com'],
            ['Roberto Canziani', 'roberto.canziani@instructor.com'],
            ['Roberto Guerrero Compean', 'roberto.guerrero.compean@instructor.com'],
            ['Robin McClellan', 'robin.mcclellan@instructor.com'],
            ['Roderick  Bates', 'roderick.bates@instructor.com'],
            ['Roger D. Peng, PhD', 'roger.d.peng.phd@instructor.com'],
            ['Rogerio Guimaraes', 'rogerio.guimaraes@instructor.com'],
            ['Rohit Rahi', 'rohit.rahi@instructor.com'],
            ['Roman Jaster', 'roman.jaster@instructor.com'],
            ['Romeo Kienzler', 'romeo.kienzler@instructor.com'],
            ['Ron Berman', 'ron.berman@instructor.com'],
            ['Ronald Fry', 'ronald.fry@instructor.com'],
            ['Ronald Guymon', 'ronald.guymon@instructor.com'],
            ['Roopa Raghavan', 'roopa.raghavan@instructor.com'],
            ['Ross Casanova', 'ross.casanova@instructor.com'],
            ['Roy H. Campbell', 'roy.h.campbell@instructor.com'],
            ['Rudi Hinds', 'rudi.hinds@instructor.com'],
            ['Rudolf Leuschner, Ph.D.', 'rudolf.leuschner.ph.d@instructor.com'],
            ['Rudy Chetty', 'rudy.chetty@instructor.com'],
            ['Russell Sayers', 'russell.sayers@instructor.com'],
            ['Ryan Ahmed', 'ryan.ahmed@instructor.com'],
            ['Ryan Lorica', 'ryan.lorica@instructor.com'],
            ['Ryan Panchadsaram', 'ryan.panchadsaram@instructor.com'],
            ['S. George Djorgovski', 's.george.djorgovski@instructor.com'],
            ['Sabrina Moore', 'sabrina.moore@instructor.com'],
            ['Sabrina Spillner', 'sabrina.spillner@instructor.com'],
            ['Sachin Jambur', 'sachin.jambur@instructor.com'],
            ['Sadie St. Lawrence', 'sadie.st.lawrence@instructor.com'],
            ['Saishruthi Swaminathan', 'saishruthi.swaminathan@instructor.com'],
            ['Sally E Shaywitz M.D.', 'sally.e.shaywitz.m.d@instructor.com'],
            ['Salman Arif', 'salman.arif@instructor.com'],
            ['Sam Jones', 'sam.jones@instructor.com'],
            ['Sam Kaufman', 'sam.kaufman@instructor.com'],
            ['Sam Meiselman', 'sam.meiselman@instructor.com'],
            ['Sam Prokopchuk', 'sam.prokopchuk@instructor.com'],
            ['Sam Siewert', 'sam.siewert@instructor.com'],
            ['Samant Bali', 'samant.bali@instructor.com'],
            ['Samarth Narula', 'samarth.narula@instructor.com'],
            ['Samaya Madhavan', 'samaya.madhavan@instructor.com'],
            ['Sammy Kimotho', 'sammy.kimotho@instructor.com'],
            ['Samuel J. Cooper', 'samuel.j.cooper@instructor.com'],
            ['Sandesh Belthangady', 'sandesh.belthangady@instructor.com'],
            ['Sandip Saha Joy', 'sandip.saha.joy@instructor.com'],
            ['Sandra Stefanic', 'sandra.stefanic@instructor.com'],
            ['Sang-Yoon Chang', 'sang.yoon.chang@instructor.com'],
            ['Sangeetha', 'sangeetha@instructor.com'],
            ['Sanjai Rayadurgam', 'sanjai.rayadurgam@instructor.com'],
            ['Sanjay Goel', 'sanjay.goel@instructor.com'],
            ['Santiago Gallino', 'santiago.gallino@instructor.com'],
            ['Sara Behdad', 'sara.behdad@instructor.com'],
            ['Sarah Amend', 'sarah.amend@instructor.com'],
            ['Sarah Hammer', 'sarah.hammer@instructor.com'],
            ['Sarah Haq', 'sarah.haq@instructor.com'],
            ['Sarah Jones', 'sarah.jones@instructor.com'],
            ['Sarah Light', 'sarah.light@instructor.com'],
            ['Saurabh Dhingra', 'saurabh.dhingra@instructor.com'],
            ['Scott  Klemmer', 'scott.klemmer@instructor.com'],
            ['Scott E. Page', 'scott.e.page@instructor.com'],
            ['Scott Plous', 'scott.plous@instructor.com'],
            ['Scott Rixner', 'scott.rixner@instructor.com'],
            ['Scott Solomon', 'scott.solomon@instructor.com'],
            ['Sean MacAvaney', 'sean.macavaney@instructor.com'],
            ['Sean McOwen', 'sean.mcowen@instructor.com'],
            ['Sean Stacey', 'sean.stacey@instructor.com'],
            ['Sebastian Ruth', 'sebastian.ruth@instructor.com'],
            ['Senthil Veeraraghavan', 'senthil.veeraraghavan@instructor.com'],
            ['Seong-Lyun Kim', 'seong.lyun.kim@instructor.com'],
            ['Seph Robinson', 'seph.robinson@instructor.com'],
            ['Serena Yeung', 'serena.yeung@instructor.com'],
            ['Sergei Savin', 'sergei.savin@instructor.com'],
            ['Sergio J Castro', 'sergio.j.castro@instructor.com'],
            ['Sergio Lacambra', 'sergio.lacambra@instructor.com'],
            ['Seungbum Hong', 'seungbum.hong@instructor.com'],
            ['Shadow Farrell', 'shadow.farrell@instructor.com'],
            ['Shambhu Upadhyaya', 'shambhu.upadhyaya@instructor.com'],
            ['Shannon Ellis, PhD', 'shannon.ellis.phd@instructor.com'],
            ['Shaowen Wang', 'shaowen.wang@instructor.com'],
            ['Sharon Horesh Bergquist, MD', 'sharon.horesh.bergquist.md@instructor.com'],
            ['Sharon Jason', 'sharon.jason@instructor.com'],
            ['Sharon Kardia', 'sharon.kardia@instructor.com'],
            ['Sharon Zhou', 'sharon.zhou@instructor.com'],
            ['Shaun Manzano', 'shaun.manzano@instructor.com'],
            ['Shawn Hymel', 'shawn.hymel@instructor.com'],
            ['Shelbee Eigenbrode', 'shelbee.eigenbrode@instructor.com'],
            ['Shelley Knuth', 'shelley.knuth@instructor.com'],
            ['Sherif A. Tawfik Abbas', 'sherif.a.tawfik.abbas@instructor.com'],
            ['Shimon Schocken', 'shimon.schocken@instructor.com'],
            ['Shirley Zou', 'shirley.zou@instructor.com'],
            ['Shree Nayar', 'shree.nayar@instructor.com'],
            ['Sid Deliwala', 'sid.deliwala@instructor.com'],
            ['Simon Murphy', 'simon.murphy@instructor.com'],
            ['Simon Smiles', 'simon.smiles@instructor.com'],
            ['Skill-Up EdTech Team', 'skill.up.edtech.team@instructor.com'],
            ['Snehan Kekre', 'snehan.kekre@instructor.com'],
            ['Sohn, Hong-Gyoo', 'sohn.hong.gyoo@instructor.com'],
            ['Solomon Tucker', 'solomon.tucker@instructor.com'],
            ['Song-Kuk Kim', 'song.kuk.kim@instructor.com'],
            ['Sonia Kumar', 'sonia.kumar@instructor.com'],
            ['Sonya Makhni', 'sonya.makhni@instructor.com'],
            ['Sorabh Kaushik', 'sorabh.kaushik@instructor.com'],
            ['Soumya Sen', 'soumya.sen@instructor.com'],
            ['Splunk Instructor', 'splunk.instructor@instructor.com'],
            ['Sriram Sankaranarayanan', 'sriram.sankaranarayanan@instructor.com'],
            ['Stacey McBrine', 'stacey.mcbrine@instructor.com'],
            ['Stacey Shanklin-Langford', 'stacey.shanklin.langford@instructor.com'],
            ['Stacey Syphus', 'stacey.syphus@instructor.com'],
            ['Stanimira Vlaeva', 'stanimira.vlaeva@instructor.com'],
            ['Stefan Szymanski', 'stefan.szymanski@instructor.com'],
            ['Steffen Foss Hansen', 'steffen.foss.hansen@instructor.com'],
            ['Stephanie Hicks, PhD', 'stephanie.hicks.phd@instructor.com'],
            ['Stephany Duda, PhD', 'stephany.duda.phd@instructor.com'],
            ['Stephen R. Lawrence', 'stephen.r.lawrence@instructor.com'],
            ['Stephen Wong', 'stephen.wong@instructor.com'],
            ['Steve Byrnes', 'steve.byrnes@instructor.com'],
            ['Steve Fritzenkotter', 'steve.fritzenkotter@instructor.com'],
            ['Steve Joordens', 'steve.joordens@instructor.com'],
            ['Steve Oney', 'steve.oney@instructor.com'],
            ['Steve Ryan', 'steve.ryan@instructor.com'],
            ['Steven Bagley', 'steven.bagley@instructor.com'],
            ['Steven Salzberg, PhD', 'steven.salzberg.phd@instructor.com'],
            ['Steven Waslander', 'steven.waslander@instructor.com'],
            ['Stewart D.  Friedman', 'stewart.d.friedman@instructor.com'],
            ['Subject Matter Expert', 'subject.matter.expert@instructor.com'],
            ['Suh, Dong Woo', 'suh.dong.woo@instructor.com'],
            ['Suk S. Brar, M.B.A.', 'suk.s.brar.m.b.a@instructor.com'],
            ['Sukyung Park', 'sukyung.park@instructor.com'],
            ['Summer Scaggs', 'summer.scaggs@instructor.com'],
            ['Sundaresan Raman', 'sundaresan.raman@instructor.com'],
            ['Sune Thorsteinsson', 'sune.thorsteinsson@instructor.com'],
            ['Sung-Hong Park', 'sung.hong.park@instructor.com'],
            ['Suraj Manikandan', 'suraj.manikandan@instructor.com'],
            ['Susan Davidson', 'susan.davidson@instructor.com'],
            ['Susan H. Rodger', 'susan.h.rodger@instructor.com'],
            ['Suzanne Hanser', 'suzanne.hanser@instructor.com'],
            ['Suzanne Healy, EdD', 'suzanne.healy.edd@instructor.com'],
            ['Sverker Werin', 'sverker.werin@instructor.com'],
            ['Svetlana Isakova', 'svetlana.isakova@instructor.com'],
            ['Svitlana (Lana) Kramar', 'svitlana.lana.kramar@instructor.com'],
            ['Swetha Maheshwary', 'swetha.maheshwary@instructor.com'],
            ['Sydney Finkelstein', 'sydney.finkelstein@instructor.com'],
            ['Sylvia Devlin, (R) (M) (QM), CIIP', 'sylvia.devlin.r.m.qm.ciip@instructor.com'],
            ['Tableau Learning Partner Instructor', 'tableau.learning.partner.instructor@instructor.com'],
            ['Takeo Igarashi', 'takeo.igarashi@instructor.com'],
            ['Tana Johnson', 'tana.johnson@instructor.com'],
            ['Tania Heap', 'tania.heap@instructor.com'],
            ['Tanmay Bakshi', 'tanmay.bakshi@instructor.com'],
            ['Tanveer', 'tanveer@instructor.com'],
            ['Tara Murphy', 'tara.murphy@instructor.com'],
            ['Taught by Meta Staff', 'taught.by.meta.staff@instructor.com'],
            ['Teach-Out Experts', 'teach.out.experts@instructor.com'],
            ['Tera Doty-Blance', 'tera.doty.blance@instructor.com'],
            ['Terry Alford', 'terry.alford@instructor.com'],
            ['Thea Lazarova', 'thea.lazarova@instructor.com'],
            ['Thelina George', 'thelina.george@instructor.com'],
            ['Themis Themistocleous', 'themis.themistocleous@instructor.com'],
            ['Theodore Henry King CLARK', 'theodore.henry.king.clark@instructor.com'],
            ['Thijs Bosker', 'thijs.bosker@instructor.com'],
            ['Thomas Abraham (HKU)', 'thomas.abraham.hku@instructor.com'],
            ['Thomas E. Parkinson', 'thomas.e.parkinson@instructor.com'],
            ['Thomas H. Sanders, Jr.', 'thomas.h.sanders.jr@instructor.com'],
            ['Thomas Hauser', 'thomas.hauser@instructor.com'],
            ['Thomas Wacker', 'thomas.wacker@instructor.com'],
            ['Tiffany Zhu', 'tiffany.zhu@instructor.com'],
            ['Tijo Thomas', 'tijo.thomas@instructor.com'],
            ['Tim Carrington', 'tim.carrington@instructor.com'],
            ['Tim Roughgarden', 'tim.roughgarden@instructor.com'],
            ['Tim Shaw', 'tim.shaw@instructor.com'],
            ['Tim White', 'tim.white@instructor.com'],
            ['Timothy Cochran', 'timothy.cochran@instructor.com'],
            ['Timothy Dunn', 'timothy.dunn@instructor.com'],
            ['Timothy M Brown', 'timothy.m.brown@instructor.com'],
            ['Timothy Scherr', 'timothy.scherr@instructor.com'],
            ['Tina Hernandez-Boussard', 'tina.hernandez.boussard@instructor.com'],
            ['Titti Mattsson', 'titti.mattsson@instructor.com'],
            ['Tom Chant', 'tom.chant@instructor.com'],
            ['Tom Hanlon', 'tom.hanlon@instructor.com'],
            ['Tom Russo', 'tom.russo@instructor.com'],
            ['Tom Yeh', 'tom.yeh@instructor.com'],
            ['Tommy Lam (HKU)', 'tommy.lam.hku@instructor.com'],
            ['Tommy Lee', 'tommy.lee@instructor.com'],
            ['Tony Dear', 'tony.dear@instructor.com'],
            ['Trent D Buskirk', 'trent.d.buskirk@instructor.com'],
            ['Trevor Thornton', 'trevor.thornton@instructor.com'],
            ['Troy L. Ott', 'troy.l.ott@instructor.com'],
            ['Tural Sadigov', 'tural.sadigov@instructor.com'],
            ['Tyson Gern', 'tyson.gern@instructor.com'],
            ['Ujjal Kumar Mukherjee', 'ujjal.kumar.mukherjee@instructor.com'],
            ['Ulf Johannsen', 'ulf.johannsen@instructor.com'],
            ['Ulrika Andersson', 'ulrika.andersson@instructor.com'],
            ['Uma Maheswari Ramalingam', 'uma.maheswari.ramalingam@instructor.com'],
            ['Umakishore Ramchandran', 'umakishore.ramchandran@instructor.com'],
            ['University of Geneva- Ines Chaieb', 'university.of.geneva.ines.chaieb@instructor.com'],
            ['University of Geneva- Jonas Demaurex', 'university.of.geneva.jonas.demaurex@instructor.com'],
            ['University of Geneva- Martin Hoesli', 'university.of.geneva.martin.hoesli@instructor.com'],
            ['University of Geneva- Michel Girardin', 'university.of.geneva.michel.girardin@instructor.com'],
            ['University of Geneva- Olivier Scaillet', 'university.of.geneva.olivier.scaillet@instructor.com'],
            ['University of Geneva- Philip Valta', 'university.of.geneva.philip.valta@instructor.com'],
            ['University of Geneva- Rajna Gibson Brandon', 'university.of.geneva.rajna.gibson.brandon@instructor.com'],
            ['University of Geneva- Tony Berrada', 'university.of.geneva.tony.berrada@instructor.com'],
            ['Unnati Narang', 'unnati.narang@instructor.com'],
            ['Upendra Rajan', 'upendra.rajan@instructor.com'],
            ['Upkar Lidder', 'upkar.lidder@instructor.com'],
            ['V. G. Vinod Vydiswaran', 'v.g.vinod.vydiswaran@instructor.com'],
            ['Valentin Jeutner', 'valentin.jeutner@instructor.com'],
            ['Vasiliki Koukoulioti', 'vasiliki.koukoulioti@instructor.com'],
            ['Venkat Viswanathan', 'venkat.viswanathan@instructor.com'],
            ['Veronika Shchiraia', 'veronika.shchiraia@instructor.com'],
            ['Vic Strecher', 'vic.strecher@instructor.com'],
            ['Vicki May', 'vicki.may@instructor.com'],
            ['Victor Geislinger', 'victor.geislinger@instructor.com'],
            ['Victoria Cornelius', 'victoria.cornelius@instructor.com'],
            ['Vijay Kumar', 'vijay.kumar@instructor.com'],
            ['Vijay Vaidyanathan, PhD', 'vijay.vaidyanathan.phd@instructor.com'],
            ['Vilhelm Persson', 'vilhelm.persson@instructor.com'],
            ['Vinay Kumar', 'vinay.kumar@instructor.com'],
            ['Vincenzo Lagani', 'vincenzo.lagani@instructor.com'],
            ['Vinita Silaparasetty', 'vinita.silaparasetty@instructor.com'],
            ['Vinod Bakthavachalam', 'vinod.bakthavachalam@instructor.com'],
            ['Viola Schiaffonati', 'viola.schiaffonati@instructor.com'],
            ['Vladimir de Turckheim', 'vladimir.de.turckheim@instructor.com'],
            ['Wade Fagen-Ulmschneider', 'wade.fagen.ulmschneider@instructor.com'],
            ['Walker Huang', 'walker.huang@instructor.com'],
            ['Wenche Wang', 'wenche.wang@instructor.com'],
            ['Wendun Wang', 'wendun.wang@instructor.com'],
            ['Wendy Martin', 'wendy.martin@instructor.com'],
            ['Wenxia Zhang', 'wenxia.zhang@instructor.com'],
            ['Wharton Teaching Staff', 'wharton.teaching.staff@instructor.com'],
            ['Whizlabs Instructor', 'whizlabs.instructor@instructor.com'],
            ['Wil van der Aalst', 'wil.van.der.aalst@instructor.com'],
            ['Will Durfee, PhD', 'will.durfee.phd@instructor.com'],
            ['William Bahn', 'william.bahn@instructor.com'],
            ['William Mead', 'william.mead@instructor.com'],
            ['William Roper', 'william.roper@instructor.com'],
            ['William Thistleton', 'william.thistleton@instructor.com'],
            ['Williams S. Ettouati, Pharm.D.', 'williams.s.ettouati.pharm.d@instructor.com'],
            ['Witold Henisz', 'witold.henisz@instructor.com'],
            ['Wounjhang Park', 'wounjhang.park@instructor.com'],
            ['Wyatt Lang', 'wyatt.lang@instructor.com'],
            ['Xintong Li', 'xintong.li@instructor.com'],
            ['Xuhu Wan', 'xuhu.wan@instructor.com'],
            ['Yaakov Chaikin', 'yaakov.chaikin@instructor.com'],
            ['Yan Luo', 'yan.luo@instructor.com'],
            ['Yan Zhang', 'yan.zhang@instructor.com'],
            ['Yang Song', 'yang.song@instructor.com'],
            ['Yang-Hann Kim', 'yang.hann.kim@instructor.com'],
            ['Yao Zhao', 'yao.zhao@instructor.com'],
            ['Yi Wang', 'yi.wang@instructor.com'],
            ['Yiwen Li', 'yiwen.li@instructor.com'],
            ['Yoav Shoham', 'yoav.shoham@instructor.com'],
            ['Younes Bensouda Mourri', 'younes.bensouda.mourri@instructor.com'],
            ['Yousef Elmehdwi', 'yousef.elmehdwi@instructor.com'],
            ['Yulong Li', 'yulong.li@instructor.com'],
            ['Yves Gourinat', 'yves.gourinat@instructor.com'],
            ['ZHANG Li', 'zhang.li@instructor.com'],
            ['Zac Robinson', 'zac.robinson@instructor.com'],
            ['Zafer Ali', 'zafer.ali@instructor.com'],
            ['Zeke Kossover', 'zeke.kossover@instructor.com'],
            ['Zhu Liu', 'zhu.liu@instructor.com'],
            ['ahmed elshorafa', 'ahmed.elshorafa@instructor.com'],
        ];

        $now = now();

        foreach ($instructors as [$name, $email]) {
            // 1. Create user
            $userId = DB::table('users')->insertGetId([
                'name'              => $name,
                'email'             => $email,
                'role'              => 'instructor',
                'password'          => Hash::make(Str::random(12)),
                'is_active'         => true,
                'timezone'          => 'Asia/Riyadh',
                'email_verified_at' => $now,
                'created_at'        => $now,
                'updated_at'        => $now,
            ]);

            // 2. Create instructor profile
            DB::table('instructor_profiles')->insert([
                'user_id'          => $userId,
                'bio'              => null,
                'specialization'   => null,
                'linkedin_url'     => null,
                'years_experience' => rand(1, 20),
                'website_url'      => null,
                'average_rating'   => round(rand(30, 50) / 10, 1),
                'created_at'       => $now,
                'updated_at'       => $now,
            ]);
        }
    }
}