<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrganizationsSeeder extends Seeder
{
    public function run(): void
    {
        $organizations = [
            'Advancing Women in Tech',
            'Akamai Technologies, Inc.',
            'Alberta Machine Intelligence Institute',
            'Alibaba Cloud Academy',
            'Amazon Web Services',
            'American Museum of Natural History',
            'Arizona State University',
            'Arm',
            'Association of International Certified Professional Accountants',
            'Atlassian',
            'Autodesk',
            'Automation Anywhere',
            'Ball State University',
            'Banco Interamericano de Desarrollo',
            'Berklee',
            'Birla Institute of Technology & Science, Pilani',
            'Bloomsbury Learning Exchange',
            'Blue Prism',
            'Board Infinity ',
            'British Council',
            'California Institute of the Arts',
            'Caltech',
            'Campus BBVA',
            'Carnegie Mellon University',
            'Case Western Reserve University',
            'CertNexus',
            'Check Point Software Technologies Ltd.',
            'Cisco Learning and Certifications',
            'Codio',
            'Columbia University',
            'Commonwealth Education Trust',
            'CompTIA',
            'ConsenSys Academy',
            'Coursera Instructor Network',
            'Coursera Project Network',
            'Dartmouth College',
            'Databricks',
            'Deep Teaching Solutions',
            'DeepLearning.AI',
            'Dell',
            'Duke University',
            'EC-Council',
            'EDHEC Business School',
            'EDUCBA',
            'EIT Digital ',
            'ESCP Business School',
            'ESSEC Business School',
            'Edge Impulse',
            'Edureka',
            'Eindhoven University of Technology',
            'Emory University',
            'Erasmus University Rotterdam',
            'Exploratorium',
            'Fractal Analytics',
            'Georgia Institute of Technology',
            'Goldsmiths, University of London',
            'Goodwill Industries International',
            'Google',
            'Google - Spectrum Sharing',
            'Google AR & VR',
            'Google Cloud',
            'HPE Aruba Networking',
            'Hebrew University of Jerusalem',
            'Howard University',
            'IBM',
            'IBM ',
            'IE Business School',
            'IEEE Geoscience and Remote Sensing Society',
            'IIMA - IIM Ahmedabad',
            'INSEAD',
            'ISAE-SUPAERO',
            'Icahn School of Medicine at Mount Sinai',
            'Illinois Tech',
            'Imperial College London',
            'Infosec',
            'Intel',
            'JetBrains',
            'Johns Hopkins University',
            'Juniper Networks',
            'Kalshoven-Gieskes Forum',
            'Karlsruhe Institute of Technology',
            'King Abdullah University of Science and Technology',
            'Knowledge Accelerators',
            'Korea Advanced Institute of Science and Technology(KAIST)',
            'L&T EduTech',
            'LearnQuest',
            'Learning for Sustainability Scotland',
            'Lund University',
            'Macquarie University',
            'MathWorks',
            'Measure What Matters',
            'MedCerts',
            'Meertens instituut (KNAW)',
            'Meta',
            'Michigan State University',
            'Microsoft',
            'MongoDB Inc.',
            'NVIDIA',
            'Nanjing University',
            'Nanyang Technological University, Singapore',
            'National Academy of Sports Medicine',
            'National Taiwan University',
            'New York Institute of Finance',
            'New York University',
            'Northeastern University ',
            'Northwestern University',
            'O.P. Jindal Global University',
            'Oracle',
            'Palo Alto Networks',
            'Parsons School of Design, The New School',
            'Peking University',
            'PepsiCo',
            'Pohang University of Science and Technology(POSTECH)',
            'Politecnico di Milano',
            'Princeton University',
            'PwC',
            'Qualcomm Academy',
            'Queen Mary University of London',
            'Red Hat',
            'Rice University',
            'Royal Holloway, University of London',
            'Rutgers the State University of New Jersey',
            'SAP',
            'SAS',
            'SOAS University of London',
            'Sapienza University of Rome',
            'Scrimba',
            'Shanghai Jiao Tong University',
            'Siemens',
            'SkillUp EdTech',
            'Splunk Inc.',
            'Stanford University',
            'Tableau Learning Partner',
            'Technical University of Denmark (DTU)',
            'Technical University of Munich (TUM)',
            'Technion - Israel Institute of Technology',
            'Tel Aviv University',
            'The Hong Kong University of Science and Technology',
            'The Linux Foundation',
            'The Pennsylvania State University',
            'The State University of New York',
            'The University of British Columbia',
            'The University of Chicago',
            'The University of Edinburgh',
            'The University of Hong Kong',
            'The University of Melbourne',
            'The University of North Carolina at Chapel Hill',
            'The University of Sydney',
            'The University of Tokyo',
            'Tsinghua University',
            'UNSW Sydney (The University of New South Wales)',
            'UiPath',
            'Universidad Austral',
            'Universiteit Leiden',
            'University System of Georgia',
            'University at Buffalo',
            'University of Alberta',
            'University of Amsterdam',
            'University of Arizona',
            'University of California San Diego',
            'University of California, Davis',
            'University of California, Irvine',
            'University of California, Santa Cruz',
            'University of Cape Town',
            'University of Colorado Boulder',
            'University of Colorado System',
            'University of Florida',
            'University of Geneva',
            'University of Glasgow ',
            'University of Illinois at Urbana-Champaign',
            'University of Kentucky',
            'University of Leeds',
            'University of London',
            'University of Manchester   ',
            'University of Maryland, College Park',
            'University of Michigan',
            'University of Minnesota',
            'University of North Texas',
            'University of Pennsylvania',
            'University of Pittsburgh',
            'University of Rochester',
            'University of Toronto',
            'University of Virginia',
            'University of Washington',
            'University of Western Australia',
            'University of Zurich',
            'VMware',
            'Vanderbilt University',
            'W3Schools',
            'Wesleyan University',
            'West Virginia University',
            'Whizlabs',
            'Yale University',
            'Yonsei University',
        ];

        foreach ($organizations as $name) {
            DB::table('organizations')->insertOrIgnore([
                'name'       => trim($name),
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}